<!DOCTYPE html>
<html lang="en"><head>
<script src="06_files/libs/clipboard/clipboard.min.js"></script>
<script src="06_files/libs/quarto-html/tabby.min.js"></script>
<script src="06_files/libs/quarto-html/popper.min.js"></script>
<script src="06_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="06_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="06_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="06_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Nicolas Cachanosky, Department of Economics and Finance">
  <meta name="dcterms.date" content="2026-09-03">
  <title>Structural Breaks</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="06_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="06_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="06_files/libs/revealjs/dist/theme/quarto-8918f2d902338036edb16d438b2b49f4.css">
  <link rel="stylesheet" href="../slides-extra.css">
  <link href="06_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="06_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="06_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="06_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#36454F" data-footer="" class="quarto-title-block">
  <h1 class="title">Structural Breaks</h1>
  <p class="subtitle">Chapter 6</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Nicolas Cachanosky, Department of Economics and Finance 
</div>
</div>
</div>

  <p class="date">2026-09-03</p>
</section>
<section id="an-assumption-we-never-stated" class="slide level2">
<h2>An Assumption We Never Stated</h2>
<blockquote>
<p>Every model in Chapters 3 through 5 rested on something we never said out loud: that the process generating the data at the end of the sample is the same process that generated it at the beginning.</p>
</blockquote>
<ul>
<li>Log GDP’s mean growth rate fell after 1984</li>
<li>Inflation went from near-unit-root persistence to clean mean reversion after Volcker</li>
<li>For many series, over many historical periods, “same process throughout” is simply false</li>
</ul>
<div class="eo-recap">
<p>A model that pools two genuinely different regimes into one set of parameter estimates doesn’t average them sensibly — it <strong>misrepresents both</strong>. This chapter builds the formal tools for detecting that misrepresentation, and for responding to it once found.</p>
</div>
<aside class="notes">
<p>Open here. The framing should feel like Chapter 5’s own cliffhanger finally getting paid off — we named a puzzle there and now we solve it. ~2 min.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-this-chapter-matters" class="slide level2">
<h2>Why This Chapter Matters</h2>
<p>Four tests, one diagnostic layer, sitting between model identification and model use:</p>
<ol type="1">
<li><strong>Chow test</strong> — do coefficients differ across two subsamples, when the break date is known?</li>
<li><strong>QLR and Bai-Perron</strong> — the same question, when the break date (or even the number of breaks) is unknown</li>
<li><strong>Zivot-Andrews</strong> — is an apparent unit root actually a broken deterministic trend in disguise?</li>
</ol>
<div class="eo-recap">
<p>Running examples: <strong>GDP growth</strong>, continued from Chapters 1–5, and a new companion, <strong>CPI inflation</strong> — the Volcker disinflation gives structural breaks a second, sharper case study.</p>
</div>
</section>
<section id="todays-roadmap" class="slide level2 outline-slide">
<h2>Today’s Roadmap</h2>
<ol type="1">
<li>When the rules change</li>
<li>The Chow test</li>
<li>From known to unknown break dates: QLR and Bai-Perron</li>
<li>Zivot-Andrews: unit roots or broken trends?</li>
<li>Responding to a detected break</li>
</ol>
</section>
<section id="when-the-rules-change" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>When the Rules Change</h2>
<div class="eo-section-label">
<p>Section 1</p>
</div>
</section>
<section id="why-economic-relationships-arent-physical-laws" class="slide level2">
<h2>Why Economic Relationships Aren’t Physical Laws</h2>
<blockquote>
<p>A physical constant doesn’t change because the world around it changed. Why would an estimated economic coefficient be any different?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Parameter stability.</strong> The assumption that a model’s coefficients are the same across every subsample of the data — maintained implicitly in every model from Chapters 3 through 5, and the object explicitly tested in this chapter.</p>
</div>
<p>Economic relationships emerge from the behavior of agents operating under specific institutions, technologies, and policy regimes. When those background conditions change <strong>durably</strong> — not transiently — the relationships governing the data change with them. A model estimated before the change carries parameter values calibrated to a world that no longer exists.</p>
</section>
<section id="what-pooling-actually-costs" class="slide level2">
<h2>What Pooling Actually Costs</h2>
<p>A single ARIMA over the full 1947–2019 GDP sample pools the Korean War boom, the postwar productivity miracle, 1970s stagflation, the Great Moderation, and the slow post-GFC recovery. Mean growth, persistence, and shock variance all differ across these sub-epochs.</p>
<div class="eo-recap">
<p><strong>Averaging is not synthesis — it’s fiction.</strong> A parameter vector fit across all of them represents none of them well.</p>
</div>
</section>
<section id="the-chapter-5-puzzle-named-precisely" class="slide level2">
<h2>The Chapter 5 Puzzle, Named Precisely</h2>
<blockquote>
<p>Recall the rolling evaluation: forecast errors didn’t scatter uniformly across the sample — they clustered. The ARIMA’s edge over the random walk shrank and vanished at <span class="math inline">\(h=4\)</span>.</p>
</blockquote>
<div class="eo-hazard">
<p><strong>That pattern is exactly what we’d expect if the model’s estimated drift and persistence were an average over two genuinely different regimes.</strong> The ARIMA anchored its forecasts on a mean growth rate reflecting the high-growth early decades more than the slower recent pace. We named this problem in Chapter 5. We did not solve it — until now.</p>
</div>
</section>
<section id="three-ways-a-process-can-break" class="slide level2">
<h2>Three Ways a Process Can Break</h2>
<div class="eo-definition">
<p><strong>Mean shift.</strong> The unconditional mean changes from <span class="math inline">\(\mu_1\)</span> to <span class="math inline">\(\mu_2\)</span> at date <span class="math inline">\(\tau\)</span> — average growth genuinely different before and after.</p>
<p><strong>Variance break.</strong> The volatility of innovations changes — exactly what the Great Moderation represents.</p>
<p><strong>Coefficient break.</strong> The dynamic structure itself changes — AR or MA coefficients, not just the mean or variance.</p>
</div>
<p>These can occur separately or together. The Great Moderation: primarily a variance break, with a modest mean shift alongside it. The Volcker disinflation: a large mean shift in inflation <em>and</em> a change in its persistence — a coefficient break.</p>
<div class="eo-recap">
<p><strong>The distinction isn’t academic — it determines which test can even detect the break, and how to respond once one is found.</strong> A test built to find coefficient instability will walk right past a pure variance change, as Section 2 demonstrates directly.</p>
</div>
</section>
<section id="the-common-structure-behind-every-test-in-this-chapter" class="slide level2">
<h2>The Common Structure Behind Every Test in This Chapter</h2>
<blockquote>
<p>Chow, QLR, Bai-Perron, Zivot-Andrews — four different names, four different statistics. What do they actually have in common?</p>
</blockquote>
<p>Every one of them asks the same underlying question: <strong>does a model that lets parameters differ across subsamples fit significantly better than one constrained to use the same parameters throughout?</strong></p>
<div class="eo-recap">
<p>If yes — at what date, or dates, does the improvement concentrate? The tests differ only in how much they assume about the break date and the number of breaks, and therefore in how they handle the statistical complications that arise when those quantities are unknown.</p>
</div>
</section>
<section id="the-chow-test" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The Chow Test</h2>
<div class="eo-section-label">
<p>Section 2</p>
</div>
</section>
<section id="a-known-break-date-the-simplest-question" class="slide level2">
<h2>A Known Break Date: The Simplest Question</h2>
<blockquote>
<p>Suppose we have a strong prior about when a break occurred. For GDP growth and the Great Moderation, that prior is 1984 Q1 — repeated across the literature, visually evident, tied to a specific economic story. Given that prior, what’s the simplest test we could run?</p>
</blockquote>
<p><span class="math display">\[
y_t = \mathbf{x}_t'\boldsymbol\beta+u_t
\]</span></p>
<div class="eo-definition">
<p><strong>Chow test</strong> (1960). <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\boldsymbol\beta\)</span> is the same in both subsamples defined by candidate break date <span class="math inline">\(\tau\)</span>. <span class="math inline">\(H_1\)</span>: it differs before and after. One of the oldest procedures in applied econometrics — transparent by design, making no attempt to be clever about what it doesn’t already know.</p>
</div>
</section>
<section id="formulation-1-the-dummy-variable-regression" class="slide level2">
<h2>Formulation 1: The Dummy-Variable Regression</h2>
<p>Define <span class="math inline">\(D_t=\mathbf{1}\{t\geq\tau\}\)</span>, interact it with every regressor including the intercept:</p>
<p><span class="math display">\[
y_t = \mathbf{x}_t'\boldsymbol\beta_1+D_t\cdot\mathbf{x}_t'\boldsymbol\delta+u_t
\]</span></p>
<p><span class="math inline">\(\boldsymbol\delta\)</span> captures the change in each coefficient at the break. Under <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\boldsymbol\delta=\mathbf{0}\)</span> — the post-break dummies add nothing.</p>
<p><span class="math display">\[
F = \frac{(\text{RSS}_R-\text{RSS}_U)/k}{\text{RSS}_U/(T-2k)} \sim F(k,T-2k) \text{ under } H_0
\]</span></p>
<div class="eo-recap">
<p><span class="math inline">\(\text{RSS}_R\)</span>: restricted model, no dummies. <span class="math inline">\(\text{RSS}_U\)</span>: unrestricted, all dummies included. This is exactly a joint significance <span class="math inline">\(F\)</span>-test on a block of dummies — the same machinery Chapter 4 used for outlier and intervention dummies.</p>
</div>
</section>
<section id="formulation-2-the-sum-of-squares-decomposition" class="slide level2">
<h2>Formulation 2: The Sum-of-Squares Decomposition</h2>
<p>Fit <strong>three</strong> separate regressions instead: the full sample, the pre-break subsample, the post-break subsample.</p>
<p><span class="math display">\[
F = \frac{(\text{RSS}_R-\text{RSS}_1-\text{RSS}_2)/k}{(\text{RSS}_1+\text{RSS}_2)/(T-2k)}
\]</span></p>
<div class="eo-recap">
<p><strong>Algebraically identical to Formulation 1</strong> — same <span class="math inline">\(F\)</span>-statistic, different route to it. This version makes the intuition explicit: it directly compares the fit of a pooled model against the fit of two subsample models estimated separately. A large <span class="math inline">\(F\)</span> means pooling discards real information.</p>
</div>
</section>
<section id="what-the-chow-test-does-and-doesnt-tell-you" class="slide level2">
<h2>What the Chow Test Does and Doesn’t Tell You</h2>
<p>A significant statistic at <span class="math inline">\(\tau\)</span> says the coefficients differ across the two subsamples <span class="math inline">\(\tau\)</span> defines. It does <strong>not</strong> say which coefficients changed, does <strong>not</strong> confirm <span class="math inline">\(\tau\)</span> is the <em>correct</em> break date, and does <strong>not</strong> rule out additional breaks elsewhere.</p>
<div class="eo-hazard">
<p><strong>The pre-testing problem.</strong> The Chow test conditions on <span class="math inline">\(\tau\)</span> being known <strong>in advance</strong>. Choosing <span class="math inline">\(\tau\)</span> by inspecting the data — picking the date where the series visually looks different — then testing at that date is circular: the data were used twice, and the resulting <span class="math inline">\(p\)</span>-value is not trustworthy. For GDP growth, 1984 Q1 is a defensible prior because it predates our analysis and comes from an external literature. Section 3’s QLR test is built specifically to remove this requirement.</p>
</div>
</section>
<section id="applied-chow-test-on-gdp-growth" class="slide level2">
<h2>Applied: Chow Test on GDP Growth</h2>
<p>AR(2) for annualized GDP growth, break at 1984 Q1 (<span class="math inline">\(k=3\)</span>: intercept plus two lags):</p>
<div class="eo-recap">
<p><strong>The joint <span class="math inline">\(F\)</span>-test does not reject</strong> (<span class="math inline">\(p=0.38\)</span>). Both Chow formulations agree exactly, confirming their algebraic equivalence. At face value: no evidence the AR(2) coefficients differ across the two subperiods.</p>
</div>
<p>But look at what the subperiod estimates actually show, next.</p>
</section>
<section id="the-subperiod-numbers-tell-a-different-story" class="slide level2">
<h2>The Subperiod Numbers Tell a Different Story</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Pre-1984</th>
<th style="text-align: center;">Post-1984</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">2.22</td>
<td style="text-align: center;">1.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residual std. dev.</td>
<td style="text-align: center;">4.44</td>
<td style="text-align: center;">2.04</td>
</tr>
</tbody>
</table>
<div class="eo-hazard">
<p><strong>The residual standard deviation roughly halves</strong> — 4.44 to 2.04, a ratio near 2.2. That’s the statistical signature of the Great Moderation, sitting right there in the subperiod table — and it’s exactly what the joint <span class="math inline">\(F\)</span>-test, built to detect <em>coefficient</em> instability, is not designed to catch. A pure variance change leaves the AR coefficients themselves largely unchanged; the Chow test looks at coefficients, so it passes right over it.</p>
</div>
</section>
<section id="confirming-it-directly-the-variance-ratio-test" class="slide level2">
<h2>Confirming It Directly: The Variance Ratio Test</h2>
<p><span class="math display">\[
F_\sigma = \frac{s^2_{\text{pre}}}{s^2_{\text{post}}} \sim F(n_{\text{pre}}-1,\,n_{\text{post}}-1) \text{ under } H_0:\sigma^2_{\text{pre}}=\sigma^2_{\text{post}}
\]</span></p>
<div class="eo-recap">
<p><strong>This test rejects decisively</strong> — a variance ratio near 5, <span class="math inline">\(p\)</span>-value indistinguishable from zero. One of the oldest tests in statistics, requiring no specialized software, and it’s the one that actually catches what’s happening.</p>
</div>
<div class="eo-hazard">
<p><strong>The complete picture, stated precisely.</strong> Chow (<span class="math inline">\(p=0.38\)</span>) and the variance ratio test (<span class="math inline">\(p\approx0\)</span>) are <strong>complementary, not redundant</strong> — each sensitive to a different feature of the distribution. Together they diagnose the Great Moderation exactly: not a coefficient break, not primarily a mean shift, but a dramatic compression of shock volatility. Section 3’s QLR and Bai-Perron results will make the same diagnosis, visually.</p>
</div>
</section>
<section id="from-known-to-unknown-break-dates-qlr-and-bai-perron" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>From Known to Unknown Break Dates: QLR and Bai-Perron</h2>
<div class="eo-section-label">
<p>Section 3</p>
</div>
</section>
<section id="when-theres-no-credible-prior" class="slide level2">
<h2>When There’s No Credible Prior</h2>
<blockquote>
<p>The Chow test worked cleanly for GDP growth — but only because we were willing to commit to 1984 Q1 before looking at the statistic. What about a series with no comparable literature — a regional housing index, a sectoral employment series?</p>
</blockquote>
<p>Choosing <span class="math inline">\(\tau\)</span> by inspecting the data, then testing at that date, is exactly the pre-testing problem Section 2 flagged.</p>
<div class="eo-recap">
<p><strong>Quandt (1960), formalized by Andrews (1993)</strong>: turn the unknown break date from a problem into a parameter. Compute the Chow <span class="math inline">\(F\)</span>-statistic at <em>every</em> candidate date in a trimmed interior of the sample, and take the maximum.</p>
</div>
</section>
<section id="the-qlr-statistic" class="slide level2">
<h2>The QLR Statistic</h2>
<p><span class="math display">\[
\text{QLR} = \sup_{\tau\in\mathcal{T}} F(\tau), \qquad \hat\tau = \arg\max_{\tau\in\mathcal{T}} F(\tau)
\]</span></p>
<div class="eo-definition">
<p><strong>Trimming.</strong> <span class="math inline">\(\mathcal{T}\)</span> excludes the first and last <span class="math inline">\(\pi_0=0.15\)</span> of the sample — standard practice, ensuring every candidate subsample has enough observations for reliable estimation.</p>
</div>
<p>At each <span class="math inline">\(\tau\in\mathcal{T}\)</span>: compute the Chow <span class="math inline">\(F\)</span>-statistic exactly as in Section 2. The break estimate is wherever the data most strongly suggest one.</p>
</section>
<section id="why-standard-critical-values-fail-here" class="slide level2">
<h2>Why Standard Critical Values Fail Here</h2>
<blockquote>
<p>A single Chow <span class="math inline">\(F\)</span>-statistic at one pre-specified <span class="math inline">\(\tau\)</span> follows <span class="math inline">\(F(k,T-2k)\)</span>. What happens once we compute it at every candidate date and keep only the maximum?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>The Davies problem.</strong> The break date <span class="math inline">\(\tau\)</span> appears only under the alternative hypothesis — it’s <strong>unidentified under the null</strong>. The maximum of many correlated <span class="math inline">\(F\)</span>-statistics is not itself <span class="math inline">\(F\)</span>-distributed; its distribution has thicker right tails, since a large maximum can appear purely by chance just from searching over many dates. Using ordinary <span class="math inline">\(F\)</span> critical values would reject the null far too often, even when it’s true.</p>
</div>
<div class="eo-recap">
<p><strong>Andrews (1993)</strong> derived the correct asymptotic critical values via the limit distribution of the supremum as a functional of a Brownian bridge. For <span class="math inline">\(k=3\)</span>, <span class="math inline">\(\pi_0=0.15\)</span>: the 5% critical value is <strong>8.85</strong> — considerably larger than the ordinary <span class="math inline">\(F(3,\infty)\)</span> value near 2.60. The gap is the price of the search.</p>
</div>
</section>
<section id="applied-qlr-on-gdp-growth" class="slide level2">
<h2>Applied: QLR on GDP Growth</h2>
<p>Two QLR sequences, computed separately: the full AR(2) coefficients (<span class="math inline">\(k=3\)</span>) and the intercept alone (<span class="math inline">\(k=1\)</span>).</p>
<div class="eo-recap">
<p><strong>Neither sequence exceeds its Andrews critical value.</strong> The AR(2)-coefficient QLR and the mean-shift QLR both fail to reject — consistent with everything Section 2 already found.</p>
</div>
</section>
<section id="the-most-important-teaching-moment-in-this-chapter" class="slide level2">
<h2>The Most Important Teaching Moment in This Chapter</h2>
<div class="eo-hazard">
<p><strong>The Great Moderation is not a break in the mean of GDP growth, and not a break in its AR dynamics.</strong> It’s a break in the <strong>variance</strong> of the innovations — and both Chow and QLR are, by construction, built to detect <em>coefficient</em> instability. A pure variance change leaves those coefficients essentially unchanged and passes straight through undetected, no matter how sophisticated the search over break dates gets.</p>
</div>
<div class="eo-recap">
<p>This is not a failure of QLR — it’s a precise statement of what it’s built to find. The variance ratio test from Section 2 already caught what these two coefficient-based tests structurally cannot. Bai-Perron, applied next, makes the same diagnosis visible directly in the data.</p>
</div>
</section>
<section id="beyond-one-break-the-bai-perron-procedure" class="slide level2">
<h2>Beyond One Break: The Bai-Perron Procedure</h2>
<blockquote>
<p>QLR answers one question: is there at least one break, and where’s the most prominent one? What if there are several — a large one and a smaller one the QLR statistic simply doesn’t surface?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Bai-Perron (1998, 2003).</strong> Treats the number of breaks <span class="math inline">\(m\)</span> and their dates <span class="math inline">\(\tau_1&lt;\cdots&lt;\tau_m\)</span> as jointly unknown. Minimizes the <strong>global</strong> sum of squared residuals over every possible partition into <span class="math inline">\(m+1\)</span> segments:</p>
<p><span class="math display">\[
(\hat\tau_1,\ldots,\hat\tau_m) = \arg\min_{\tau_1,\ldots,\tau_m}\sum_{j=1}^{m+1}\sum_{t=\tau_{j-1}+1}^{\tau_j}(y_t-\mathbf{x}_t'\boldsymbol\beta_j)^2
\]</span></p>
</div>
<p>An efficient dynamic programming algorithm computes this for every <span class="math inline">\(m\)</span> up to some maximum, without brute-force enumeration of every possible partition.</p>
</section>
<section id="testing-for-at-least-one-break-then-counting" class="slide level2">
<h2>Testing for At Least One Break, Then Counting</h2>
<div class="eo-definition">
<p><strong>UDmax and WDmax.</strong> Run the QLR-style test separately for <span class="math inline">\(m=1,2,\ldots,m_{\max}\)</span> breaks, combine into one omnibus statistic testing “is there any break at all?” <strong>UDmax</strong>: the raw maximum across those tests. <strong>WDmax</strong>: the same idea, reweighted for equal power against each alternative. In practice, the two almost always agree.</p>
</div>
<p>Once either rejects: the <strong>sequential <span class="math inline">\(F\)</span>-test</strong> determines <span class="math inline">\(m\)</span> itself — start at <span class="math inline">\(m=1\)</span>, test whether adding one more break significantly reduces the residual sum of squares, stop when it doesn’t.</p>
<div class="eo-recap">
<p>Same Davies problem as QLR — both statistics have non-standard limit distributions, with critical values tabulated by Bai and Perron (1998).</p>
</div>
</section>
<section id="applied-bai-perron-on-gdp-growth" class="slide level2">
<h2>Applied: Bai-Perron on GDP Growth</h2>

<img data-src="../../chapters/06/chapter_06_files/figure-html/fig-baiperron-output-2.png" class="img-fluid r-stretch" alt="GDP growth with Bai-Perron detected segment means overlaid, showing a volatility reduction in the mid-1980s and shifts in mean growth rate across segments, NBER recessions shaded"><p><em>The detected segments visibly compress in <strong>volatility</strong> around the mid-1980s — the Great Moderation, recovered directly from the data with no imposed prior about when it should occur. Compare the algorithm’s dates against the 1984 Q1 prior from Chow and QLR: alignment strengthens the case that the break is a genuine feature of the process; where dates differ, that difference is itself informative — the break may be gradual rather than a single clean date.</em></p>
<aside class="notes">
<p>This is the visual payoff of the whole “variance break, not coefficient break” arc from Sections 2-3. Let the figure do the confirming — the segments should visibly narrow in spread post-1984 even as their means don’t shift dramatically. ~2 min.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zivot-andrews-unit-roots-or-broken-trends" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Zivot-Andrews: Unit Roots or Broken Trends?</h2>
<div class="eo-section-label">
<p>Section 4</p>
</div>
</section>
<section id="a-problem-left-unresolved-since-chapter-4" class="slide level2">
<h2>A Problem Left Unresolved Since Chapter 4</h2>
<blockquote>
<p>Chapter 4 flagged that when ADF and KPSS conflict, one should suspect a structural break and investigate subsamples. That advice told us what to do <em>after</em> finding a conflict. It never gave us a formal test for whether a break is actually there, or when.</p>
</blockquote>
<div class="eo-hazard">
<p><strong>The deeper problem: a broken deterministic trend can look almost identical to a unit root.</strong> Both produce slow, persistent drift wandering from one level to another. ADF is built to distinguish a random walk from stationarity around a <em>stable</em> mean or trend — it will often fail to reject the unit root null when the truth is stationary with a one-time shift. The result: a <strong>false diagnosis of nonstationarity</strong>, and a false justification for differencing a series that never needed it.</p>
</div>
</section>
<section id="a-new-running-example-cpi-inflation" class="slide level2">
<h2>A New Running Example: CPI Inflation</h2>
<blockquote>
<p>GDP growth is already a first difference — <span class="math inline">\(\Delta\log\text{GDP}_t\)</span> — and inherits near-stationarity from that transformation directly. Why does inflation behave differently?</p>
</blockquote>
<p>CPI inflation is the change in the log <strong>price level</strong>, and the price level itself may or may not be integrated — the inflation rate’s own persistence depends entirely on the monetary policy regime in force.</p>
<div class="eo-recap">
<p><strong>The Volcker disinflation, precisely.</strong> Pre-1979: accommodative policy let inflation drift upward with supply shocks and political pressure — 3% in the late 1960s to over 13% by 1979. Volcker’s response: unprecedented rate increases, triggering the 1980 and 1981-82 recessions, inflation down below 4% by 1983. Post-Volcker: inflation-targeting, anchored near a low single-digit rate with dramatically reduced persistence.</p>
</div>
</section>
<section id="why-adf-alone-gets-this-wrong" class="slide level2">
<h2>Why ADF Alone Gets This Wrong</h2>
<p>A standard ADF on the full 1947–2019 inflation series sees a long, slow drift — 3% up to 13%, back down to 2–3%. That trajectory looks exactly like the kind of nonstationary path that makes ADF lean toward <strong>not rejecting</strong> the unit root null.</p>
<div class="eo-hazard">
<p><strong>But the true process may be stationary in both sub-regimes</strong>, with the apparent unit root nothing more than an artifact of pooling across the Volcker break. This is precisely the scenario Zivot-Andrews (1992) was built to disentangle.</p>
</div>
</section>
<section id="the-zivot-andrews-model" class="slide level2">
<h2>The Zivot-Andrews Model</h2>
<p>Model C — a break in both intercept and trend, the most general and default variant:</p>
<p><span class="math display">\[
y_t = c+\beta t+\gamma DU_t(\tau)+\delta DT_t(\tau)+\alpha y_{t-1}+\sum_{j=1}^k d_j\Delta y_{t-j}+\varepsilon_t
\]</span></p>
<div class="eo-definition">
<p><span class="math inline">\(DU_t(\tau)=\mathbf{1}\{t&gt;\tau\}\)</span>: a level-shift dummy. <span class="math inline">\(DT_t(\tau)=(t-\tau)\cdot\mathbf{1}\{t&gt;\tau\}\)</span>: a slope-shift dummy. <span class="math inline">\(H_0:\alpha=1\)</span> (unit root). <span class="math inline">\(H_1:|\alpha|&lt;1\)</span> (stationary around a <strong>broken</strong> deterministic trend).</p>
</div>
</section>
<section id="the-za-statistic" class="slide level2">
<h2>The ZA Statistic</h2>
<p><span class="math display">\[
\text{ZA} = \inf_{\tau\in\mathcal{T}} t_{\hat\alpha}(\tau)
\]</span></p>
<p>The break date <span class="math inline">\(\tau\)</span> is endogenous — tested at every candidate date, keeping the <strong>most negative</strong> <span class="math inline">\(t\)</span>-statistic on <span class="math inline">\(\hat\alpha\)</span>: the strongest available evidence against the unit root null.</p>
<div class="eo-recap">
<p><strong>Same Davies problem as QLR</strong>, once again — searching over <span class="math inline">\(\tau\)</span> means the statistic doesn’t follow a standard <span class="math inline">\(t\)</span>-distribution. Zivot and Andrews (1992) derived asymptotic critical values via simulation. For Model C: the 5% critical value is approximately <strong><span class="math inline">\(-5.08\)</span></strong>.</p>
</div>
</section>
<section id="applied-za-on-cpi-inflation" class="slide level2">
<h2>Applied: ZA on CPI Inflation</h2>
<div class="eo-hazard">
<p><strong>Neither ADF (<span class="math inline">\(-1.54\)</span>) nor ZA (<span class="math inline">\(-4.71\)</span>) rejects the unit root null at conventional significance</strong> — even though ZA’s statistic is meaningfully more negative than ADF’s, confirming that allowing for a break moves the evidence in the expected direction. And the estimated ZA break date, 1952-01, falls near the trimming boundary — <strong>not</strong> at the Volcker disinflation.</p>
</div>
<div class="eo-recap">
<p><strong>A known, honest limitation, not a hidden one.</strong> When the true break is a mean shift inside a highly persistent AR process, ZA’s power is limited — the most-negative <span class="math inline">\(t\)</span>-statistic can land near the sample edges rather than at the genuine break. This is exactly why the companion figure, next, uses the known 1983 Q1 Volcker date directly rather than the test’s own estimate — the economic argument for the break doesn’t depend on ZA successfully locating it.</p>
</div>
</section>
<section id="contrast-gdp-growth-rejects-decisively" class="slide level2">
<h2>Contrast: GDP Growth Rejects Decisively</h2>
<div class="eo-recap">
<p><strong>For GDP growth, both tests reject outright</strong> — ADF at <span class="math inline">\(-5.95^{***}\)</span>, ZA at <span class="math inline">\(-6.54^{***}\)</span>. GDP growth is stationary, full stop, with or without allowing for a break. This is the expected result: growth is already differenced, so stationarity is exactly what lets us model it with ARMA dynamics in the first place. (Its own ZA break date also lands near the trimming boundary — the same power limitation, not a genuine early break.)</p>
</div>
<p>The contrast is the real lesson: <strong>ZA’s honest limitation shows up specifically on the harder, more persistent series (inflation) — not on the easier one (growth).</strong></p>
</section>
<section id="seeing-the-volcker-break-directly" class="slide level2">
<h2>Seeing the Volcker Break Directly</h2>

<img data-src="../../chapters/06/chapter_06_files/figure-html/fig-za-cpi-output-1.png" class="img-fluid r-stretch" alt="CPI inflation with subperiod means before and after the 1983 Q1 Volcker disinflation, showing the full-sample mean misrepresenting both regimes"><p><em>The full-sample mean (copper, dashed) sits above the entire post-Volcker inflation path — it misrepresents both regimes simultaneously, exactly Section 1’s “pooling is fiction” point made visible. The two subperiod means (sky blue) capture the regime shift the ZA test was designed to detect, even though its own break-date search struggled to land precisely on it.</em></p>
</section>
<section id="responding-to-a-detected-break" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Responding to a Detected Break</h2>
<div class="eo-section-label">
<p>Section 5</p>
</div>
</section>
<section id="diagnosis-is-not-a-prescription" class="slide level2">
<h2>Diagnosis Is Not a Prescription</h2>
<blockquote>
<p>A significant Chow statistic, a Bai-Perron-detected date — these are diagnostic information. They don’t tell you what to actually do next.</p>
</blockquote>
<p>Three options, ordered from simplest to most flexible — the econometric decision belongs to the researcher, not the test.</p>
</section>
<section id="option-1-subperiod-estimation" class="slide level2">
<h2>Option 1: Subperiod Estimation</h2>
<p>Split the sample at the estimated break date; estimate separate models on each regime. For GDP growth at 1984 Q1: an AR(2) (or ARIMA) on 1947 Q2–1983 Q4, a separate one on 1984 Q1–2019 Q4.</p>
<div class="eo-recap">
<p><strong>The tradeoff is precision for relevance.</strong> Smaller subsamples mean less precise estimates — but for quarterly GDP growth, ~148 pre-break and ~144 post-break observations are both large enough for reliable ARIMA estimation. <strong>Right default when</strong>: the break is large, the post-break subsample is long enough, and there’s no strong reason to expect another break soon.</p>
</div>
</section>
<section id="option-2-dummy-variables" class="slide level2">
<h2>Option 2: Dummy Variables</h2>
<p>Retain the full sample; add dummies to model the break directly — exactly the Section 2 dummy-regression structure.</p>
<p><span class="math display">\[
y_t = \mu+\gamma D_t+\phi_1y_{t-1}+\cdots+\varepsilon_t
\]</span></p>
<div class="eo-definition">
<p><strong>Level-shift dummy</strong>, for a pure mean shift like Volcker: <span class="math inline">\(D_t=0\)</span> pre-break gives intercept <span class="math inline">\(\mu\)</span>; <span class="math inline">\(D_t=1\)</span> post-break gives <span class="math inline">\(\mu+\gamma\)</span>. A <strong>trend-shift</strong> variant handles a change in slope instead (<span class="math inline">\(DT_t=t\cdot D_t\)</span>); the most general form allows both simultaneously — exactly ZA’s Model C, as a fixed regression rather than a date search.</p>
</div>
<div class="eo-recap">
<p><strong>Uses all <span class="math inline">\(T\)</span> observations</strong>, more efficient than subperiod estimation — at the cost of forcing pre- and post-break innovations to share one variance. Directly connects to Chapter 4’s outlier and intervention dummies: this is that same framework, generalized from single-observation blips to permanent level shifts.</p>
</div>
</section>
<section id="option-3-split-sample-forecasting" class="slide level2">
<h2>Option 3: Split-Sample Forecasting</h2>
<p>A hybrid: use the full sample for estimation precision, but generate forecasts leaning on the post-break regime — or let a <strong>rolling window</strong> do this automatically.</p>
<div class="eo-recap">
<p><strong>Chapter 5’s rolling evaluation was already doing this, implicitly.</strong> The 40-quarter window, by design, dropped most of the high-volatility pre-1984 data from the training sample by the time evaluation reached the 2000s. This chapter’s tests provide the formal justification for a choice Chapter 5 made on practical grounds alone.</p>
</div>
</section>
<section id="option-4-when-breaks-recur-markov-switching" class="slide level2">
<h2>Option 4: When Breaks Recur — Markov-Switching</h2>
<blockquote>
<p>The first three options all treat a break as one permanent shift. What about a process that switches back and forth — expansions and recessions, calm and turbulent markets?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Markov-switching</strong> (Hamilton, 1989). Parameters follow an unobserved Markov chain: at each date, the process is in one of <span class="math inline">\(K\)</span> regimes, transitioning according to a fixed probability matrix <span class="math inline">\(\mathbf{P}\)</span>.</p>
<p><span class="math display">\[
\hat{\mathbf{P}} = \begin{pmatrix}0.95&amp;0.05\\0.25&amp;0.75\end{pmatrix}
\]</span></p>
</div>
<div class="eo-recap">
<p>95% chance of staying in expansion, 5% of entering recession; 25% chance of recovering, 75% of remaining. Expected duration <span class="math inline">\(1/(1-p_{ii})\)</span>: expansions ~20 quarters, recessions ~4 — broadly matching postwar US cycles. The recurrent generalization of everything in this chapter; formal treatment deferred to Chapter 10.</p>
</div>
</section>
<section id="applied-comparing-the-strategies" class="slide level2">
<h2>Applied: Comparing the Strategies</h2>
<p>Full-sample ARIMA(1,1,1)+drift (Chapter 5’s baseline) vs.&nbsp;post-break ARIMA vs.&nbsp;ARIMA with a level-shift dummy — same 40-quarter rolling window, <span class="math inline">\(h=1\)</span>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Strategy</th>
<th style="text-align: center;">RMSE</th>
<th style="text-align: center;">vs.&nbsp;Full-Sample</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Full-sample ARIMA</td>
<td style="text-align: center;">2.297</td>
<td style="text-align: center;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Post-break ARIMA</td>
<td style="text-align: center;">2.175</td>
<td style="text-align: center;"><strong>0.947</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">ARIMA + level-shift dummy</td>
<td style="text-align: center;">2.282</td>
<td style="text-align: center;">0.993</td>
</tr>
</tbody>
</table>
<div class="eo-recap">
<p><strong>Both break-aware strategies beat the full-sample baseline.</strong> The post-break ARIMA wins by more — using only low-volatility post-1984 data for estimation buys a bigger gain than the dummy variant, which retains the full history and only shifts the intercept, so it still inherits some contamination from the high-variance pre-break period. Whether these differences are <em>statistically</em> distinguishable is Chapter 5’s Diebold-Mariano test.</p>
</div>
<div class="eo-hazard">
<p><strong>Why no MAPE here?</strong> GDP growth crosses zero and turns sharply negative in recessions — the 2008-09 contraction alone (annualized growth near <span class="math inline">\(-8.9\%\)</span>) would produce MAPE values an order of magnitude larger than any other quarter. Same Chapter 5 lesson: MAPE breaks down for series that approach zero. RMSE and MAE are the right summary statistics here.</p>
</div>
</section>
<section id="recap" class="slide level2 recap-slide" data-background-color="#87A96B" data-footer="false">
<h2>Recap</h2>
<p>We built a complete diagnostic layer for structural instability. The Chow test asked whether coefficients differ across a <em>known</em> break date — and its failure to reject for GDP growth turned out to be the chapter’s central lesson: the Great Moderation is a variance break, not a coefficient break, invisible to any test built to look at coefficients alone. QLR and Bai-Perron removed the known-date requirement, confirming the same diagnosis with a formal search and a multi-break visual. Zivot-Andrews tackled the harder confusion between a unit root and a broken trend — honestly, including its own real limitation on a highly persistent series like inflation. And Section 5 turned diagnosis into practice: subperiod estimation, dummy variables, split-sample forecasting, each earning real, measurable forecast-accuracy gains.</p>
<div class="eo-recap">
<p>Every test in this chapter operated on a single equation. But GDP growth and inflation are not independent — they’re jointly determined by policy, demand, and supply shocks together. Single-equation tools have nothing to say about that relationship.</p>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p>This chapter’s tools all live within a single-equation framework — one series, tested for stability, modeled on its own history. But we’ve had no way to ask whether the <em>relationship</em> between GDP growth and inflation is stable, how a shock to one propagates to the other, or how much of GDP growth’s variance traces back to inflation shocks versus its own. These are inherently multivariate questions.</p>
<p>Chapter 7 builds that framework. The <strong>reduced-form VAR</strong> lets GDP growth and inflation — and any other variables we choose — depend on each other’s lags, replacing a single equation with a system. <strong>Granger causality</strong> formalizes whether one series helps predict another beyond what its own history already contains. The <strong>structural VAR</strong> adds identifying restrictions — Cholesky decomposition, sign restrictions — that let us speak to <em>causal</em> propagation, not just prediction. <strong>Impulse response functions</strong> then trace the full dynamic path after a shock, made visible in a way no single-equation model ever could.</p>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<div class="eo-keyterms">
<dl>
<dt>Structural break / Parameter stability</dt>
<dd>
A permanent change in one or more parameters of the data-generating process; parameter stability is the (often implicit) assumption every model in Chapters 3–5 relied on.
</dd>
<dt>Mean shift / Variance break / Coefficient break</dt>
<dd>
Three distinct ways a process can change — in its level, its shock volatility, or its dynamic structure — each requiring a different detection strategy.
</dd>
<dt>Chow test</dt>
<dd>
<span class="math inline">\(F\)</span>-test for equal coefficients across a <em>known</em> break date; dummy-variable and sum-of-squares formulations are algebraically identical.
</dd>
<dt>Pre-testing problem</dt>
<dd>
Choosing a break date by inspecting the data, then testing at that date, invalidates the test’s critical values.
</dd>
<dt>Quandt likelihood ratio (QLR) test</dt>
<dd>
The Chow <span class="math inline">\(F\)</span>-statistic maximized over every candidate break date; requires Andrews (1993) critical values due to the Davies problem.
</dd>
<dt>Davies problem</dt>
<dd>
A nuisance parameter (the break date) appearing only under <span class="math inline">\(H_1\)</span> makes the null distribution non-standard.
</dd>
<dt>Bai-Perron procedure / UDmax, WDmax</dt>
<dd>
Jointly estimates the number and location of multiple unknown breaks by minimizing global residual sum of squares; UDmax/WDmax test for the existence of at least one break.
</dd>
<dt>Great Moderation</dt>
<dd>
The post-1984 decline in US GDP growth volatility — a variance break, not a coefficient break; the chapter’s canonical illustration.
</dd>
<dt>Zivot-Andrews test</dt>
<dd>
Unit root test allowing a single unknown break in the deterministic trend; distinguishes a broken trend from a genuine unit root.
</dd>
<dt>Volcker disinflation</dt>
<dd>
The sharp, deliberate reduction of US inflation beginning 1979 — a mean shift and a coefficient (persistence) break simultaneously.
</dd>
<dt>Subperiod estimation / Dummy variables / Split-sample forecasting</dt>
<dd>
Three practical responses to a detected break — re-estimate separately, add shift dummies to the pooled model, or let a rolling window adapt automatically.
</dd>
<dt>Markov-switching model</dt>
<dd>
Parameters follow an unobserved Markov chain across <span class="math inline">\(K\)</span> regimes with fixed transition probabilities — the recurrent generalization of a one-time structural break.
</dd>
</dl>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ECON-5371 · Time Series Analysis and Forecasting</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="06_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="06_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="06_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="06_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="06_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="06_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="06_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="06_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="06_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="06_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>