<!DOCTYPE html>
<html lang="en"><head>
<script src="08_files/libs/clipboard/clipboard.min.js"></script>
<script src="08_files/libs/quarto-html/tabby.min.js"></script>
<script src="08_files/libs/quarto-html/popper.min.js"></script>
<script src="08_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="08_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="08_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="08_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Nicolas Cachanosky, Department of Economics and Finance">
  <meta name="dcterms.date" content="2026-08-27">
  <title>Cointegration and the Vector Error Correction Model</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="08_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="08_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="08_files/libs/revealjs/dist/theme/quarto-8918f2d902338036edb16d438b2b49f4.css">
  <link rel="stylesheet" href="../slides-extra.css">
  <link href="08_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="08_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="08_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="08_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#36454F" data-footer="" class="quarto-title-block">
  <h1 class="title">Cointegration and the Vector Error Correction Model</h1>
  <p class="subtitle">Chapter 8</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Nicolas Cachanosky, Department of Economics and Finance 
</div>
</div>
</div>

  <p class="date">2026-08-27</p>
</section>
<section id="the-boundary-chapter-7-left-standing" class="slide level2">
<h2>The Boundary Chapter 7 Left Standing</h2>
<blockquote>
<p>Chapter 7 built the complete VAR toolkit — Granger causality, structural identification, impulse responses — but relied on one assumption throughout: every variable stationary. What happens to two genuinely <span class="math inline">\(I(1)\)</span> series that can’t just be differenced away?</p>
</blockquote>
<ul>
<li>Differencing restores stationarity — but it <strong>discards</strong> every piece of information about the long-run relationship between the variables</li>
<li>If two series are bound together by economics — driven by the same underlying force — that binding is exactly what gets thrown away</li>
<li>Neither “estimate in levels anyway” nor “difference everything” is actually correct</li>
</ul>
<div class="eo-recap">
<p>This chapter resolves the boundary properly. Not a patch on Chapter 7 — a genuinely new representation of the VAR that keeps the long-run relationship explicit instead of discarding it.</p>
</div>
<aside class="notes">
<p>Open here, directly continuing Chapter 7’s closing slide. The framing should feel like the promised resolution finally arriving. ~2 min.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-this-chapter-matters" class="slide level2">
<h2>Why This Chapter Matters</h2>
<p>One new representation of the VAR, three tools built on top of it:</p>
<ol type="1">
<li><strong>The Johansen test</strong> — how many long-run equilibrium relationships does this system actually have?</li>
<li><strong>The VECM</strong> — reparameterize the VAR to make short-run dynamics and long-run correction two distinct, interpretable pieces</li>
<li><strong>VECM forecasting</strong> — quantify precisely what differencing throws away</li>
</ol>
<div class="eo-recap">
<p>Running example: the <strong>US yield curve</strong> — the 10-year Treasury yield and the 3-month T-bill rate. Both driven by the same monetary policy and inflation expectations; their spread is one of the most closely watched recession indicators in macroeconomics.</p>
</div>
</section>
<section id="todays-roadmap" class="slide level2 outline-slide">
<h2>Today’s Roadmap</h2>
<ol type="1">
<li>Why differencing isn’t enough</li>
<li>Cointegration, precisely</li>
<li>The <span class="math inline">\(\Pi\)</span> matrix and the path to testing</li>
<li>The Johansen trace test</li>
<li>The vector error correction model</li>
<li>VECM diagnostics and common pitfalls</li>
<li>IRFs and the VECM forecast comparison</li>
</ol>
</section>
<section id="why-differencing-isnt-enough" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Why Differencing Isn’t Enough</h2>
<div class="eo-section-label">
<p>Section 1</p>
</div>
</section>
<section id="two-rates-one-underlying-story" class="slide level2">
<h2>Two Rates, One Underlying Story</h2>
<blockquote>
<p>The 10-year Treasury yield and the 3-month T-bill rate rarely move in lockstep quarter to quarter — but do they ever drift permanently apart?</p>
</blockquote>
<div class="eo-definition">
<p><strong>The expectations hypothesis (EH) of the term structure.</strong> The long rate approximately equals the average of expected future short rates, plus a roughly constant term premium. If true: both rates share the <em>same</em> underlying stochastic trend — the path of monetary policy and inflation expectations — and their spread should be <strong>stationary</strong>, fluctuating around a constant premium rather than wandering without bound.</p>
</div>
<p>Both rates, individually, show every sign of a unit root — persistent, slow-moving, no fixed level to revert to. Exactly <span class="math inline">\(I(1)\)</span> behavior, by Chapter 1 and 4’s criteria.</p>
</section>
<section id="why-a-levels-var-fails" class="slide level2">
<h2>Why a Levels VAR Fails</h2>
<blockquote>
<p>If both rates are <span class="math inline">\(I(1)\)</span>, why not just estimate the VAR from Chapter 7 directly on their levels?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>Every inferential tool from Chapter 7 breaks.</strong> <span class="math inline">\(t\)</span>-statistics, <span class="math inline">\(F\)</span>-statistics, and information criteria all assume standard asymptotic distributions that simply don’t apply once the underlying variables are nonstationary. Lag selection becomes unreliable; Granger-causality tests have nonstandard null distributions; impulse responses <strong>don’t converge to zero</strong> as <span class="math inline">\(h\to\infty\)</span> — they approach a nonzero constant, since a genuine unit root process has no fixed point for a shock to decay back toward.</p>
</div>
</section>
<section id="why-differencing-also-fails" class="slide level2">
<h2>Why Differencing Also Fails</h2>
<blockquote>
<p>The natural fix: difference both rates first, restore stationarity, apply Chapter 7’s tools cleanly. What’s lost?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>Everything about the long-run relationship between the two rates.</strong> A VAR in <span class="math inline">\(\Delta r^{10}_t,\Delta r^{3m}_t\)</span> can only ever describe how <em>changes</em> in one rate relate to changes in the other — it has no mechanism to notice that the <em>levels</em> are supposed to stay close together. If the two series are genuinely cointegrated, a differenced VAR is systematically misspecified: it omits an entire economically meaningful mechanism.</p>
</div>
<div class="eo-recap">
<p><strong>The stakes, concretely.</strong> If the spread is truly mean-reverting around a term premium, a differenced VAR treats today’s spread as “just another random walk realization” — with no pull back toward that premium at all. Section 7’s forecast comparison quantifies exactly how large this omission turns out to be.</p>
</div>
</section>
<section id="what-a-resolution-requires" class="slide level2">
<h2>What a Resolution Requires</h2>
<blockquote>
<p>Neither extreme works — not levels, not differences. What property would a correct model need?</p>
</blockquote>
<p>A framework that: (1) recognizes both series are individually <span class="math inline">\(I(1)\)</span>; (2) simultaneously recognizes their spread is <strong>not</strong> <span class="math inline">\(I(1)\)</span> — it’s stationary; and (3) uses that stationary combination as an explicit, estimable piece of the model, rather than an assumption smuggled in or an information discarded.</p>
<div class="eo-recap">
<p><strong>This is exactly what cointegration formalizes</strong>, and exactly what the vector error correction model is built to estimate. Section 2 makes the concept precise.</p>
</div>
</section>
<section id="cointegration-precisely" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Cointegration, Precisely</h2>
<div class="eo-section-label">
<p>Section 2</p>
</div>
</section>
<section id="how-two-nonstationary-series-cancel" class="slide level2">
<h2>How Two Nonstationary Series Cancel</h2>
<blockquote>
<p>Two individually <span class="math inline">\(I(1)\)</span> series, algebraically — under what condition does a combination of them ever become stationary?</p>
</blockquote>
<p>Suppose both accumulate the <strong>same</strong> stochastic trend:</p>
<p><span class="math display">\[
y_t = \mu_y+\tau_t+u_t^y, \qquad x_t = \mu_x+\tau_t+u_t^x, \qquad \tau_t=\tau_{t-1}+\eta_t
\]</span></p>
<p><span class="math inline">\(\tau_t\)</span>: a shared random walk. <span class="math inline">\(u_t^y,u_t^x\)</span>: stationary disturbances. Each series individually is <span class="math inline">\(I(1)\)</span> — <span class="math inline">\(\tau_t\)</span> enters both. Now form the difference:</p>
<p><span class="math display">\[
y_t-x_t = (\mu_y-\mu_x)+(u_t^y-u_t^x)
\]</span></p>
<div class="eo-recap">
<p><strong>The common trend cancels exactly.</strong> What remains is a constant plus a difference of two stationary processes — itself stationary. Two <span class="math inline">\(I(1)\)</span> series produce a stationary combination precisely when they share a common stochastic trend that cancels in the combination.</p>
</div>
</section>
<section id="the-formal-definition" class="slide level2">
<h2>The Formal Definition</h2>
<div class="eo-definition">
<p><strong>Cointegration.</strong> Two <span class="math inline">\(I(1)\)</span> series <span class="math inline">\(y_t,x_t\)</span> are cointegrated if there exists a constant <span class="math inline">\(\beta\)</span> such that <span class="math inline">\(z_t=y_t-\beta x_t\)</span> is <span class="math inline">\(I(0)\)</span>. <span class="math inline">\((1,-\beta)'\)</span>: the <strong>cointegrating vector</strong>. <span class="math inline">\(z_t\)</span>: the <strong>equilibrium residual</strong> or <strong>error correction term</strong>.</p>
</div>
<div class="eo-recap">
<p><strong>Not unique without normalization</strong> — <span class="math inline">\((c,-c\beta)'\)</span> is equally valid for any <span class="math inline">\(c\neq0\)</span>; we normalize the coefficient on <span class="math inline">\(y_t\)</span> to 1. Cointegrated series aren’t “always equal” or “always close” — their <em>deviations</em> from each other are bounded. Shocks push them apart temporarily; an equilibrating force eventually pulls them back.</p>
</div>
</section>
<section id="reading-the-equilibrium-residual-economically" class="slide level2">
<h2>Reading the Equilibrium Residual Economically</h2>
<p>If <span class="math inline">\(z_t=y_t-\beta x_t\)</span> has mean <span class="math inline">\(\mu_z\)</span>, then in the long run, when <span class="math inline">\(z_t\)</span> sits at its mean:</p>
<p><span class="math display">\[
y_t = \mu_z+\beta x_t
\]</span></p>
<div class="eo-recap">
<p><strong><span class="math inline">\(\beta\)</span> is the long-run response of <span class="math inline">\(y_t\)</span> to a permanent change in <span class="math inline">\(x_t\)</span>.</strong> The equilibrium residual measures the <em>current</em> deviation from that relationship — positive means <span class="math inline">\(y_t\)</span> sits above its long-run value given <span class="math inline">\(x_t\)</span>; negative means below. For the yield curve, <span class="math inline">\(\beta=1\)</span> would mean the two rates move one-for-one long-run, and <span class="math inline">\(r^{10}_t-r^{3m}_t\)</span> is stationary around a constant term premium <span class="math inline">\(\mu_z\)</span> — exactly the EH prediction.</p>
</div>
</section>
<section id="from-pairs-to-systems-cointegrating-rank" class="slide level2">
<h2>From Pairs to Systems: Cointegrating Rank</h2>
<blockquote>
<p>With more than two <span class="math inline">\(I(1)\)</span> variables, could there be more than one independent long-run relationship at once?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Cointegrating rank <span class="math inline">\(r\)</span>.</strong> The number of linearly independent cointegrating vectors among <span class="math inline">\(n\)</span> <span class="math inline">\(I(1)\)</span> variables, <span class="math inline">\(0\leq r\leq n-1\)</span>.</p>
<p><span class="math inline">\(r=0\)</span>: no cointegration, <span class="math inline">\(n\)</span> independent trends, differenced VAR correct. <span class="math inline">\(0&lt;r&lt;n\)</span>: <span class="math inline">\(r\)</span> equilibrium relationships, <span class="math inline">\(n-r\)</span> independent common trends, VECM correct. <span class="math inline">\(r=n\)</span>: impossible — would mean the variables are stationary, contradicting <span class="math inline">\(I(1)\)</span>.</p>
</div>
<p>For our two-variable yield system: only <span class="math inline">\(r=0\)</span> or <span class="math inline">\(r=1\)</span> are possible. The EH predicts <span class="math inline">\(r=1\)</span> — Section 4’s Johansen test verifies this formally.</p>
</section>
<section id="the-common-trends-representation" class="slide level2">
<h2>The Common Trends Representation</h2>
<p><span class="math display">\[
\mathbf{y}_t = \boldsymbol\Gamma\mathbf{f}_t+\boldsymbol\xi_t
\]</span></p>
<div class="eo-definition">
<p><strong>Stock-Watson (1988) common trends representation.</strong> <span class="math inline">\(\mathbf{f}_t\)</span>: <span class="math inline">\((n-r)\times1\)</span> vector of common stochastic trends (random walks). <span class="math inline">\(\boldsymbol\Gamma\)</span>: <span class="math inline">\(n\times(n-r)\)</span> loading matrix. <span class="math inline">\(\boldsymbol\xi_t\)</span>: stationary disturbances. Each variable is a combination of the <span class="math inline">\(n-r\)</span> common trends plus a transitory component.</p>
</div>
<div class="eo-recap">
<p><strong>Cointegration means fewer independent trends than variables.</strong> The <span class="math inline">\(n-r\)</span> trends are genuinely shared; the <span class="math inline">\(r\)</span> cointegrating vectors are exactly the combinations that eliminate all of them simultaneously. For the yield curve with <span class="math inline">\(r=1\)</span>: one shared trend — the monetary policy/inflation-expectations cycle — and one cointegrating vector, the spread, that cancels it.</p>
</div>
</section>
<section id="applied-confirming-both-rates-are-i1" class="slide level2">
<h2>Applied: Confirming Both Rates Are <span class="math inline">\(I(1)\)</span></h2>
<p>ADF and KPSS on the 10-year yield and 3-month rate, intercept-only (rates don’t trend indefinitely in one direction):</p>
<div class="eo-recap">
<p><strong>Both tests agree, for both series.</strong> ADF fails to reject the unit root null (<span class="math inline">\(p=0.74\)</span>, <span class="math inline">\(p=0.58\)</span>); KPSS rejects stationarity (statistics of 0.65, 0.72, both exceeding the 5% critical value of 0.46). Confirmed <span class="math inline">\(I(1)\)</span> — precisely the joint-testing discipline from Chapter 1 and 4, now applied to both variables before anything multivariate begins.</p>
</div>
</section>
<section id="seeing-the-cancellation-directly" class="slide level2">
<h2>Seeing the Cancellation Directly</h2>
<div class="eo-columns-figure">
<div>
<p>Top: both rates re-based to 1954 Q1 — drifting without bound, sharing the same broad shape through the inflationary 1970s and the post-Volcker decades.</p>
<p>Bottom: the spread — visibly mean-reverting, no long-run drift, occasionally negative (terracotta) but always correcting back.</p>
</div>
<div>
<p><img data-src="../../chapters/08/chapter_08_files/figure-html/fig-spread-output-1.png" class="img-fluid" alt="Top panel: 10-year yield and 3-month T-bill rate re-based to 1954, both drifting. Bottom panel: the term spread, stationary around a positive mean, with inversions shaded"></p>
</div>
</div>
<div class="eo-recap">
<p><strong>Every recession in the sample was preceded by an inversion.</strong> The alignment between terracotta (inverted spread) and grey (NBER recession) shading is close to exact — one of the most robust empirical regularities in macroeconomics, and this chapter builds the formal language for understanding exactly why it holds.</p>
</div>
</section>
<section id="the-pi-matrix-and-the-path-to-testing" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The <span class="math inline">\(\Pi\)</span> Matrix and the Path to Testing</h2>
<div class="eo-section-label">
<p>Section 3</p>
</div>
</section>
<section id="from-the-levels-var-to-a-testable-restriction" class="slide level2">
<h2>From the Levels VAR to a Testable Restriction</h2>
<blockquote>
<p>Section 1 showed we can’t estimate a levels VAR <em>or</em> a differenced VAR safely. Is there a third representation that reveals cointegration as a specific, testable algebraic restriction?</p>
</blockquote>
<p>Start from the familiar VAR(<span class="math inline">\(p\)</span>) in levels:</p>
<p><span class="math display">\[
\mathbf{y}_t = \mathbf{c}+\mathbf{A}_1\mathbf{y}_{t-1}+\cdots+\mathbf{A}_p\mathbf{y}_{t-p}+\mathbf{u}_t
\]</span></p>
<div class="eo-recap">
<p>Subtract <span class="math inline">\(\mathbf{y}_{t-1}\)</span> from both sides and collect terms — <strong>the same algebra Chapter 4 used to convert an AR(<span class="math inline">\(p\)</span>) into an ADF regression</strong>, now applied to the whole vector system at once.</p>
</div>
</section>
<section id="the-vector-error-correction-representation" class="slide level2">
<h2>The Vector Error Correction Representation</h2>
<p><span class="math display">\[
\Delta\mathbf{y}_t = \mathbf{c}+\boldsymbol\Pi\mathbf{y}_{t-1}+\boldsymbol\Gamma_1\Delta\mathbf{y}_{t-1}+\cdots+\boldsymbol\Gamma_{p-1}\Delta\mathbf{y}_{t-p+1}+\mathbf{u}_t
\]</span></p>
<p><span class="math display">\[
\boldsymbol\Pi = \sum_{i=1}^p\mathbf{A}_i-\mathbf{I}_n, \qquad \boldsymbol\Gamma_i=-\sum_{j=i+1}^p\mathbf{A}_j
\]</span></p>
<div class="eo-recap">
<p><strong>Looks like a VAR in differences, plus one extra term.</strong> <span class="math inline">\(\boldsymbol\Gamma_i\)</span>: the short-run dynamics — how changes today depend on recent changes, exactly the differenced-VAR content. <span class="math inline">\(\boldsymbol\Pi\mathbf{y}_{t-1}\)</span>: the <strong>only</strong> term touching lagged <em>levels</em> — this is where all the long-run information lives.</p>
</div>
</section>
<section id="what-the-rank-of-boldsymbolpi-reveals" class="slide level2">
<h2>What the Rank of <span class="math inline">\(\boldsymbol\Pi\)</span> Reveals</h2>
<blockquote>
<p><span class="math inline">\(\boldsymbol\Pi\)</span> is <span class="math inline">\(n\times n\)</span>. What does its rank actually tell us?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>Three cases, three completely different models.</strong> <span class="math inline">\(\text{rank}(\boldsymbol\Pi)=0\)</span>: <span class="math inline">\(\boldsymbol\Pi=\mathbf{0}\)</span>, the levels term vanishes entirely — this <em>is</em> the differenced VAR, correct exactly when there’s no cointegration. <span class="math inline">\(\text{rank}(\boldsymbol\Pi)=n\)</span>: full rank, meaning the variables are stationary in levels — contradicts the <span class="math inline">\(I(1)\)</span> assumption we started from, ruled out by design. <span class="math inline">\(0&lt;\text{rank}(\boldsymbol\Pi)=r&lt;n\)</span>: the genuinely interesting case.</p>
</div>
</section>
<section id="the-reduced-rank-case-where-the-vecm-comes-from" class="slide level2">
<h2>The Reduced-Rank Case: Where the VECM Comes From</h2>
<p>When <span class="math inline">\(0&lt;r&lt;n\)</span>: <span class="math inline">\(\boldsymbol\Pi\)</span> factors as the product of two <span class="math inline">\(n\times r\)</span> matrices,</p>
<p><span class="math display">\[
\boldsymbol\Pi = \boldsymbol\alpha\boldsymbol\beta'
\]</span></p>
<div class="eo-recap">
<p><span class="math inline">\(\boldsymbol\beta\)</span>: the <span class="math inline">\(r\)</span> cointegrating vectors, as columns. <span class="math inline">\(\boldsymbol\alpha\)</span>: the speed-of-adjustment coefficients. <span class="math inline">\(\boldsymbol\Pi\mathbf{y}_{t-1}=\boldsymbol\alpha\boldsymbol\beta'\mathbf{y}_{t-1}\)</span> becomes an <span class="math inline">\(n\times1\)</span> vector of <span class="math inline">\(r\)</span> <strong>stationary</strong> error correction terms, each weighted by how strongly that variable responds. This factorization <strong>is</strong> the VECM — Section 5 develops it fully.</p>
</div>
<div class="eo-hazard">
<p><strong>Everything in the Johansen procedure flows from the rank of <span class="math inline">\(\boldsymbol\Pi\)</span>.</strong> The test doesn’t examine cointegrating vectors directly — it examines eigenvalues of a matrix derived from <span class="math inline">\(\boldsymbol\Pi\)</span>. A zero eigenvalue: rank-deficient in that direction. <span class="math inline">\(r\)</span> nonzero eigenvalues: <span class="math inline">\(\text{rank}(\boldsymbol\Pi)=r\)</span>, <span class="math inline">\(r\)</span> cointegrating relationships. Counting nonzero eigenvalues <strong>is</strong> determining cointegrating rank.</p>
</div>
</section>
<section id="solving-a-concrete-boldsymbolpi-by-hand" class="slide level2">
<h2>Solving a Concrete <span class="math inline">\(\boldsymbol\Pi\)</span> by Hand</h2>
<p>A <span class="math inline">\(2\times2\)</span> example calibrated to the yield curve:</p>
<p><span class="math display">\[
\boldsymbol\Pi = \begin{pmatrix}-0.05&amp;0.05\\0.12&amp;-0.12\end{pmatrix}
\]</span></p>
<p>The second column is exactly <span class="math inline">\(-1\times\)</span> the first — <strong>rank 1 by inspection</strong>, one eigenvalue must be zero. Confirm via <span class="math inline">\(\det(\boldsymbol\Pi-\lambda\mathbf{I})=0\)</span>:</p>
<p><span class="math display">\[
(-0.05-\lambda)(-0.12-\lambda)-(0.05)(0.12)=0 \;\Longrightarrow\; \lambda^2+0.17\lambda=0
\]</span></p>
<p><span class="math display">\[
\lambda(\lambda+0.17)=0 \;\Longrightarrow\; \lambda_1=0,\quad \lambda_2=-0.17
\]</span></p>
</section>
<section id="reading-off-boldsymbolalpha-and-boldsymbolbeta-directly" class="slide level2">
<h2>Reading Off <span class="math inline">\(\boldsymbol\alpha\)</span> and <span class="math inline">\(\boldsymbol\beta\)</span> Directly</h2>
<p>With <span class="math inline">\(r=1\)</span>, write <span class="math inline">\(\boldsymbol\Pi=\boldsymbol\alpha\boldsymbol\beta'\)</span>:</p>
<p><span class="math display">\[
\boldsymbol\alpha=\begin{pmatrix}-0.05\\0.12\end{pmatrix}, \qquad \boldsymbol\beta'=\begin{pmatrix}1&amp;-1\end{pmatrix}
\]</span></p>
<div class="eo-recap">
<p><strong>The cointegrating vector <span class="math inline">\((1,-1)'\)</span> is exactly the EH restriction</strong> — <span class="math inline">\(y_{1t}-y_{2t}=\text{constant}\)</span>, the 10-year yield minus the 3-month rate equals a constant term premium. And the adjustment coefficients have an immediate economic reading: when the spread narrows below its long-run mean (negative error correction term), the long rate <em>rises</em> by <span class="math inline">\(0.05\times\)</span> the deviation and the short rate <em>falls</em> by <span class="math inline">\(0.12\times\)</span> — both forces widening the spread back toward equilibrium. The short rate adjusts more strongly, consistent with the Fed actively managing short rates while long rates move more sluggishly.</p>
</div>
</section>
<section id="from-a-known-boldsymbolpi-to-an-estimated-one" class="slide level2">
<h2>From a Known <span class="math inline">\(\boldsymbol\Pi\)</span> to an Estimated One</h2>
<div class="eo-hazard">
<p><strong>We never actually observe <span class="math inline">\(\boldsymbol\Pi\)</span> — we estimate it from data, and the estimated eigenvalues are themselves random.</strong> The hand-solved example had exact zeros and clean rank; a real sample never does. The Johansen test uses the <em>magnitudes</em> of the sample eigenvalues to make formal inference about how many population eigenvalues are genuinely nonzero — separating “close to zero, probably actually zero” from “far enough from zero to represent a real cointegrating relationship.”</p>
</div>
<div class="eo-recap">
<p>That formal inference procedure — the trace and maximum-eigenvalue statistics — is Section 4.</p>
</div>
</section>
<section id="the-johansen-trace-test" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The Johansen Trace Test</h2>
<div class="eo-section-label">
<p>Section 4</p>
</div>
</section>
<section id="where-the-eigenvalues-actually-come-from" class="slide level2">
<h2>Where the Eigenvalues Actually Come From</h2>
<div class="eo-definition">
<p><strong>Not eigenvalues of <span class="math inline">\(\hat{\boldsymbol\Pi}\)</span> directly.</strong> A <strong>reduced-rank regression</strong> first concentrates out the short-run dynamics <span class="math inline">\(\boldsymbol\Gamma_i\Delta\mathbf{y}_{t-i}\)</span>, then finds the <span class="math inline">\(r\)</span> linear combinations of <span class="math inline">\(\mathbf{y}_{t-1}\)</span> most correlated with <span class="math inline">\(\Delta\mathbf{y}_t\)</span> after that partialling-out. The resulting <span class="math inline">\(\hat\lambda_i\)</span> are <strong>squared canonical correlations</strong> between <span class="math inline">\(\Delta\mathbf{y}_t\)</span> and <span class="math inline">\(\mathbf{y}_{t-1}\)</span>, lying in <span class="math inline">\([0,1]\)</span>.</p>
</div>
<div class="eo-recap">
<p><span class="math inline">\(\hat\lambda_i\)</span> near 0: that combination of <span class="math inline">\(\mathbf{y}_{t-1}\)</span> has no predictive content for <span class="math inline">\(\Delta\mathbf{y}_t\)</span> — nonstationary. <span class="math inline">\(\hat\lambda_i\)</span> near 1: strong predictive content — stationary, a genuine cointegrating combination.</p>
</div>
</section>
<section id="two-test-statistics" class="slide level2">
<h2>Two Test Statistics</h2>
<div class="eo-definition">
<p><strong>Trace statistic.</strong> <span class="math inline">\(H_0:\text{rank}\leq r\)</span> vs.&nbsp;<span class="math inline">\(H_1:\text{rank}&gt;r\)</span>:</p>
<p><span class="math display">\[
\lambda_{\text{trace}}(r) = -T\sum_{i=r+1}^n\ln(1-\hat\lambda_i)
\]</span></p>
<p><strong>Maximum eigenvalue statistic.</strong> <span class="math inline">\(H_0:\text{rank}=r\)</span> vs.&nbsp;<span class="math inline">\(H_1:\text{rank}=r+1\)</span> specifically:</p>
<p><span class="math display">\[
\lambda_{\max}(r,r+1) = -T\ln(1-\hat\lambda_{r+1})
\]</span></p>
</div>
<div class="eo-recap">
<p><strong>Trace as the primary test</strong> — better power when true rank exceeds the null by more than one; max-eigenvalue as a check, more focused but less powerful in that case. Neither follows a standard <span class="math inline">\(\chi^2\)</span>; critical values depend on <span class="math inline">\(n-r\)</span> and the deterministic specification, tabulated and reported automatically by software.</p>
</div>
</section>
<section id="sequential-testing-to-find-hat-r" class="slide level2">
<h2>Sequential Testing to Find <span class="math inline">\(\hat r\)</span></h2>
<p>Start at the most restrictive null, <span class="math inline">\(r=0\)</span>; test against <span class="math inline">\(r\geq1\)</span>. Reject <span class="math inline">\(\to\)</span> move to <span class="math inline">\(r=1\)</span>, test against <span class="math inline">\(r\geq2\)</span>. Continue until first failing to reject — that rank is <span class="math inline">\(\hat r\)</span>.</p>
<div class="eo-hazard">
<p><strong>Sequential testing inflates the Type I error rate.</strong> Each step is its own hypothesis test; the overall procedure does not control the error rate at the nominal level across all steps combined — in practice, a tendency to slightly over-reject low rank. Remedies: a small-sample Bartlett correction where available, or — more commonly — treat results as strongly suggestive and check robustness by estimating VECMs at adjacent ranks.</p>
</div>
</section>
<section id="choosing-the-deterministic-specification" class="slide level2">
<h2>Choosing the Deterministic Specification</h2>
<blockquote>
<p>Before running the test, does the cointegrating relationship itself have a nonzero mean? Do the levels drift deterministically?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Case 2</strong> (restricted intercept, no trend): <span class="math inline">\(\boldsymbol\beta'\mathbf{y}_t=\mu_0\)</span>, nonzero long-run mean, but no deterministic drift in the variables. <strong>Case 3</strong> (unrestricted intercept): both the cointegrating relation and short-run equations get an intercept, letting levels drift linearly while the cointegrating relation itself doesn’t trend.</p>
</div>
<div class="eo-recap">
<p><strong>For the yield curve: Case 2.</strong> Interest rates don’t trend in one direction indefinitely — even the post-Volcker decline was a long but bounded episode — and the EH implies the spread fluctuates around a <em>constant</em> term premium, no trend. <code>coint_johansen(det_order=0)</code> is Case 2 exactly.</p>
</div>
</section>
<section id="applied-setting-up-the-test" class="slide level2">
<h2>Applied: Setting Up the Test</h2>
<p>Lag selection for the levels VAR: BIC picks <span class="math inline">\(p=2\)</span>; AIC picks <span class="math inline">\(p=8\)</span>.</p>
<div class="eo-recap">
<p><strong>We proceed with AIC’s <span class="math inline">\(p=8\)</span></strong> — Section 6’s residual diagnostics show <span class="math inline">\(p=2\)</span> leaves significant autocorrelation in the short-rate equation, confirming BIC is too parsimonious here. Same “criteria disagree, diagnostics resolve it” pattern as Chapters 4 and 7. The lag order passed to <code>coint_johansen</code> is <span class="math inline">\(p-1=7\)</span>, since the VECM representation has <span class="math inline">\(p-1\)</span> differenced lags.</p>
</div>
</section>
<section id="applied-the-trace-test-result" class="slide level2">
<h2>Applied: The Trace Test Result</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(H_0\)</span>: rank <span class="math inline">\(\leq\)</span></th>
<th style="text-align: center;">Eigenvalue</th>
<th style="text-align: center;">Trace</th>
<th style="text-align: center;">CV 95%</th>
<th style="text-align: center;">Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.107</td>
<td style="text-align: center;">33.33</td>
<td style="text-align: center;">15.49</td>
<td style="text-align: center;"><strong>Reject</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.014</td>
<td style="text-align: center;">3.61</td>
<td style="text-align: center;">3.84</td>
<td style="text-align: center;">Fail to reject</td>
</tr>
</tbody>
</table>
<div class="eo-recap">
<p><strong>At <span class="math inline">\(r=0\)</span>: trace far exceeds the critical value — reject decisively.</strong> At <span class="math inline">\(r=1\)</span>: trace sits just below the critical value — fail to reject. Estimated rank <span class="math inline">\(\hat r=1\)</span>: one cointegrating relationship, one common stochastic trend — exactly the EH prediction from Section 1, and exactly what the hand-solved <span class="math inline">\(2\times2\)</span> example previewed.</p>
</div>
</section>
<section id="seeing-the-eigenvalues-themselves" class="slide level2">
<h2>Seeing the Eigenvalues Themselves</h2>

<img data-src="../../chapters/08/chapter_08_files/figure-html/fig-eigenvalues-output-1.png" class="img-fluid r-stretch" alt="Left panel: Johansen eigenvalues for the yield curve system, showing the first substantially positive and the second near zero. Right panel: trace statistics against 95 percent critical values"><p><em>Left: the first eigenvalue (0.107) sits clearly above zero — a genuinely stationary combination exists. The second (0.014) sits close to zero — no second cointegrating relationship, consistent with a single common stochastic trend. Right: the trace statistics against their critical values, visually confirming the reject-then-fail-to-reject pattern from the table.</em></p>
</section>
<section id="the-vector-error-correction-model" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The Vector Error Correction Model</h2>
<div class="eo-section-label">
<p>Section 5</p>
</div>
</section>
<section id="from-boldsymbolpi-to-an-estimable-model" class="slide level2">
<h2>From <span class="math inline">\(\boldsymbol\Pi\)</span> to an Estimable Model</h2>
<p>Substituting Section 3’s factorization <span class="math inline">\(\boldsymbol\Pi=\boldsymbol\alpha\boldsymbol\beta'\)</span> directly into the VECM representation:</p>
<p><span class="math display">\[
\Delta\mathbf{y}_t = \mathbf{c}+\boldsymbol\alpha\boldsymbol\beta'\mathbf{y}_{t-1}+\boldsymbol\Gamma_1\Delta\mathbf{y}_{t-1}+\cdots+\boldsymbol\Gamma_{p-1}\Delta\mathbf{y}_{t-p+1}+\mathbf{u}_t
\]</span></p>
<div class="eo-recap">
<p><strong>Two genuinely distinct components, not a relabeling.</strong> The short-run piece — <span class="math inline">\(\boldsymbol\Gamma_i\Delta\mathbf{y}_{t-i}\)</span> — captures how today’s changes depend on recent changes, exactly the differenced-VAR content. The long-run piece — <span class="math inline">\(\boldsymbol\alpha\boldsymbol\beta'\mathbf{y}_{t-1}\)</span> — captures how today’s changes depend on <strong>last period’s deviation from equilibrium</strong>. A differenced VAR has no equivalent to this second piece at all.</p>
</div>
</section>
<section id="written-out-for-the-yield-curve" class="slide level2">
<h2>Written Out for the Yield Curve</h2>
<p>With <span class="math inline">\(r=1\)</span>, the two-variable system equation by equation:</p>
<p><span class="math display">\[
\begin{aligned}
\Delta r^{10}_t &amp;= c_1+\alpha_1\underbrace{(r^{10}_{t-1}-\beta r^{3m}_{t-1})}_{\text{error correction term}}+\gamma_{11}\Delta r^{10}_{t-1}+\gamma_{12}\Delta r^{3m}_{t-1}+u_{1t} \\
\Delta r^{3m}_t &amp;= c_2+\alpha_2\underbrace{(r^{10}_{t-1}-\beta r^{3m}_{t-1})}_{\text{error correction term}}+\gamma_{21}\Delta r^{10}_{t-1}+\gamma_{22}\Delta r^{3m}_{t-1}+u_{2t}
\end{aligned}
\]</span></p>
<div class="eo-recap">
<p><strong>The term in parentheses is exactly the equilibrium residual from Section 2</strong> — the lagged deviation of the long rate from its long-run relationship with the short rate. Positive: long rate above equilibrium. Negative: inverted yield curve. <span class="math inline">\(\alpha_1,\alpha_2\)</span> determine how strongly each rate responds to that disequilibrium.</p>
</div>
</section>
<section id="testing-the-theory-implied-restriction" class="slide level2">
<h2>Testing the Theory-Implied Restriction</h2>
<blockquote>
<p>The EH predicts <span class="math inline">\(\beta=1\)</span> exactly. Does the freely estimated Johansen <span class="math inline">\(\hat\beta\)</span> come anywhere close?</p>
</blockquote>
<div class="eo-recap">
<p><strong><span class="math inline">\(\hat\beta=1.0218\)</span> — differing from the theoretical value of 1 by just 0.02.</strong> Close enough that the restriction is unlikely to be rejected by a formal test; imposing <span class="math inline">\(\beta=1\)</span> exactly would make the error correction term literally the raw yield spread, the most familiar quantity in the term-structure literature. The empirical work below uses the freely estimated <span class="math inline">\(\hat\beta=1.0218\)</span> — the equilibrium residual is exactly Section 2’s Johansen residual.</p>
</div>
</section>
<section id="how-estimation-actually-proceeds" class="slide level2">
<h2>How Estimation Actually Proceeds</h2>
<div class="eo-definition">
<p><strong>Reduced-rank regression, in two steps.</strong> Step 1 (already done, Section 4): the Johansen procedure estimates <span class="math inline">\(\hat{\boldsymbol\beta}\)</span> as the eigenvectors corresponding to the <span class="math inline">\(r\)</span> largest canonical-correlation eigenvalues. Step 2: given <span class="math inline">\(\hat{\boldsymbol\beta}\)</span>, estimate <span class="math inline">\(\hat{\boldsymbol\alpha}\)</span> and <span class="math inline">\(\hat{\boldsymbol\Gamma}_i\)</span> by <strong>OLS</strong> of <span class="math inline">\(\Delta\mathbf{y}_t\)</span> on <span class="math inline">\(\hat{\boldsymbol\beta}'\mathbf{y}_{t-1}\)</span> and the lagged differences — an ordinary regression, once <span class="math inline">\(\hat{\boldsymbol\beta}\)</span> is treated as known.</p>
</div>
<p><code>statsmodels</code>’ <code>VECM</code> class runs both steps in one call — <code>coint_rank=1</code>, <code>deterministic="ci"</code> matching Section 4’s Case 2 specification exactly.</p>
</section>
<section id="applied-the-full-vecm-estimate" class="slide level2">
<h2>Applied: The Full VECM Estimate</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 38%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\hat\beta\)</span> (on 3-month rate)</td>
<td style="text-align: center;"><span class="math inline">\(1.0218\)</span></td>
<td style="text-align: left;">Long-run one-for-one comovement</td>
</tr>
<tr class="even">
<td style="text-align: left;">Term premium</td>
<td style="text-align: center;"><span class="math inline">\(\approx1.35\)</span>pp</td>
<td style="text-align: left;">Matches sample mean spread (1.47pp)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\hat\alpha_1\)</span> (10-year yield)</td>
<td style="text-align: center;"><span class="math inline">\(-0.056^{**}\)</span></td>
<td style="text-align: left;">Long rate falls when spread above equilibrium</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\hat\alpha_2\)</span> (3-month rate)</td>
<td style="text-align: center;"><span class="math inline">\(0.084^{**}\)</span></td>
<td style="text-align: left;">Short rate rises when spread above equilibrium</td>
</tr>
</tbody>
</table>
<div class="eo-recap">
<p><strong>Both signs are exactly right, and both are significant at 5%.</strong> When the spread sits above its long-run mean, the long rate corrects downward and the short rate corrects upward — both forces narrowing the gap back toward equilibrium, precisely the mean-reverting mechanism the yield-curve figure showed visually in Section 2.</p>
</div>
</section>
<section id="reading-the-asymmetry-weak-exogeneity" class="slide level2">
<h2>Reading the Asymmetry: Weak Exogeneity</h2>
<blockquote>
<p>Why does the short rate (<span class="math inline">\(\hat\alpha_2=0.084\)</span>) respond roughly 50% more strongly than the long rate (<span class="math inline">\(\hat\alpha_1=-0.056\)</span>)?</p>
</blockquote>
<div class="eo-recap">
<p><strong>Consistent with how each rate is actually set.</strong> The Fed actively manages short rates in response to economic conditions; long rates move more sluggishly, shaped by slower-moving expectations. If <span class="math inline">\(\hat\alpha_i=0\)</span> exactly for some variable, that variable is <strong>weakly exogenous</strong> — it still appears in the cointegrating vector (it matters for the long-run relationship) but bears none of the adjustment burden itself. Neither rate is weakly exogenous here — both actively participate in restoring equilibrium, just at different speeds.</p>
</div>
</section>
<section id="putting-short-run-and-long-run-together" class="slide level2">
<h2>Putting Short-Run and Long-Run Together</h2>
<p>Own-rate momentum from <span class="math inline">\(\hat{\boldsymbol\Gamma}_1\)</span> (0.225 for the long rate, 0.234 for the short rate) tends to <strong>prolong</strong> rate movements in the short run — the additional lags beyond the first contribute only modest, largely insignificant increments.</p>
<div class="eo-recap">
<p><strong>Momentum and error correction pull in opposite directions on different time scales.</strong> Short-run momentum can push a rate further from equilibrium quarter to quarter; the error-correction force works against that momentum once the deviation grows large enough. Together: a system that can <strong>overshoot in the short run but reverts in the medium run</strong> — exactly the cyclical spread behavior visible in Section 2’s figure.</p>
</div>
</section>
<section id="vecm-diagnostics-and-common-pitfalls" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>VECM Diagnostics and Common Pitfalls</h2>
<div class="eo-section-label">
<p>Section 6</p>
</div>
</section>
<section id="the-same-standard-now-applied-to-the-vecm" class="slide level2">
<h2>The Same Standard, Now Applied to the VECM</h2>
<blockquote>
<p>A VECM is correctly specified only if its residuals are white noise — serially uncorrelated, homoskedastic, approximately normal. Where have we seen this checklist before?</p>
</blockquote>
<div class="eo-recap">
<p><strong>Exactly Chapter 7’s VAR residual criteria, unchanged.</strong> Portmanteau test for serial correlation, Jarque-Bera for normality, a brief heteroskedasticity check. The VECM residuals are <span class="math inline">\(\hat{\mathbf{u}}_t=\Delta\mathbf{y}_t-\hat{\boldsymbol\alpha}\hat z_{t-1}-\sum_i\hat{\boldsymbol\Gamma}_i\Delta\mathbf{y}_{t-i}\)</span> — one vector per observation.</p>
</div>
</section>
<section id="applied-the-residuals-pass-with-one-honest-caveat" class="slide level2">
<h2>Applied: The Residuals Pass, With One Honest Caveat</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: center;">Long Rate</th>
<th style="text-align: center;">Short Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ljung-Box Q(8)</td>
<td style="text-align: center;">1.7 (<span class="math inline">\(p=0.99\)</span>)</td>
<td style="text-align: center;">11.0 (<span class="math inline">\(p=0.20\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jarque-Bera</td>
<td style="text-align: center;"><span class="math inline">\(55.3^{***}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(610.5^{***}\)</span></td>
</tr>
</tbody>
</table>
<div class="eo-recap">
<p><strong>Ljung-Box fails to reject for both equations</strong> — the AIC-selected <span class="math inline">\(p=8\)</span> fully absorbs the serial correlation the shorter BIC-preferred order left behind.</p>
</div>
<div class="eo-hazard">
<p><strong>Jarque-Bera rejects normality strongly in both — entirely attributable to the Volcker-episode outliers (1980-82).</strong> This does <strong>not</strong> invalidate the VECM estimates or the cointegration conclusions, which rely on asymptotic theory, not normality. Fat tails from one dramatic historical episode are a data feature to note, not a specification flaw to fix.</p>
</div>
</section>
<section id="the-real-question-does-the-ect-actually-matter" class="slide level2">
<h2>The Real Question: Does the ECT Actually Matter?</h2>
<blockquote>
<p>Residuals passing in isolation only says the VECM is internally consistent. The sharper question: is it actually <strong>better</strong> than a differenced VAR that omits the error correction term entirely?</p>
</blockquote>
<p>Estimate a differenced VAR at the same lag order; compare residual ACFs directly.</p>
<div class="eo-hazard">
<p><strong>A genuinely surprising result: the two models’ residual ACFs are nearly identical.</strong> At the quarterly frequency, the <span class="math inline">\(\hat\alpha\)</span> coefficients (0.056, 0.084) move each rate by only a few basis points per quarter — swamped by short-run momentum and noise. <strong>The ECT’s contribution is invisible in short-run residual diagnostics.</strong></p>
</div>
<div class="eo-recap">
<p><strong>This is not a case against the VECM — it’s a statement about <em>where</em> cointegration’s value shows up.</strong> Not in one-step-ahead residual behavior, but in long-horizon forecast accuracy. Section 7’s 40-quarter comparison is the definitive test.</p>
</div>
</section>
<section id="pitfall-1-over-differencing" class="slide level2">
<h2>Pitfall 1: Over-Differencing</h2>
<div class="eo-hazard">
<p><strong>If the true system is cointegrated but you estimate a differenced VAR anyway, the ECT’s omission accumulates as forecast error over long horizons</strong> — invisible short-run, as we just saw, but decisive at long horizons. Section 7’s forecast comparison quantifies exactly how large: implied long-run spreads of 1.37pp (VECM) vs.&nbsp;0.35pp (differenced VAR).</p>
</div>
</section>
<section id="pitfall-2-spurious-cointegration" class="slide level2">
<h2>Pitfall 2: Spurious Cointegration</h2>
<div class="eo-hazard">
<p><strong>The Johansen test can reject “no cointegration” even when none genuinely exists</strong> — particularly in small samples or when the system contains an undetected structural break. The yield curve application is protected because the theory is strong: the EH gives a <em>precise</em> prediction for what <span class="math inline">\(\boldsymbol\beta\)</span> should look like, and <span class="math inline">\(\hat\beta=1.0218\)</span> lands almost exactly there. <strong>When theory is silent about the cointegrating vector, treat a significant trace statistic with more skepticism</strong> — robustness checks across subsamples become essential, not optional.</p>
</div>
</section>
<section id="pitfall-3-rank-misspecification" class="slide level2">
<h2>Pitfall 3: Rank Misspecification</h2>
<div class="eo-hazard">
<p><strong>Costs are asymmetric.</strong> Rank too low: omits genuine error correction terms, reduces to the over-differencing problem above. Rank too high: introduces spurious error correction terms that add noise without explanatory power. Section 4’s sequential procedure guards against this but <strong>slightly over-rejects at low rank</strong> due to multiple testing — when any step’s result is marginal, estimating VECMs at adjacent ranks and comparing diagnostics is good practice, not excessive caution.</p>
</div>
</section>
<section id="cointegration-and-structural-breaks-dont-mix-well" class="slide level2">
<h2>Cointegration and Structural Breaks Don’t Mix Well</h2>
<blockquote>
<p>The Johansen test assumes the cointegrating relationship is stable across the <em>entire</em> sample. What if it isn’t?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>A shift in the long-run relationship — a monetary regime change, a secular trend in underlying economic forces — degrades the test’s power and can produce misleading rank conclusions.</strong> Chapter 6’s structural break tools are the right response when a break is suspected: test for cointegration within stable subsamples, or allow the cointegrating intercept itself to shift via a dummy variable. The yield curve avoids this over 1954-2019 — but the log consumption/log income pair (Section 1) shows exactly how a secular shift, there in the saving rate, can destabilize an otherwise well-motivated cointegrating relationship.</p>
</div>
</section>
<section id="irfs-and-the-vecm-forecast-comparison" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>IRFs and the VECM Forecast Comparison</h2>
<div class="eo-section-label">
<p>Section 7</p>
</div>
</section>
<section id="structural-irfs-one-change-from-chapter-7" class="slide level2">
<h2>Structural IRFs, One Change From Chapter 7</h2>
<p>Identification proceeds exactly as Chapter 7: a Cholesky ordering. Long rate first, short rate second — the long rate can move contemporaneously with a shock before the Fed reacts within the same quarter; a shock to the short rate takes one period to reach the long rate.</p>
<div class="eo-recap">
<p><strong>What’s genuinely new: the impulse responses don’t decay to zero.</strong> In a stationary VAR, every response converges to zero — shocks are transitory by construction. In a VECM with <span class="math inline">\(r=1\)</span>, responses converge to a <strong>nonzero permanent level</strong> instead. This is not a bug — it’s the direct signature of a shared stochastic trend that a shock can genuinely, permanently shift.</p>
</div>
</section>
<section id="applied-the-irfs-themselves" class="slide level2">
<h2>Applied: The IRFs Themselves</h2>

<img data-src="../../chapters/08/chapter_08_files/figure-html/fig-vecm-irf-output-1.png" class="img-fluid r-stretch" alt="2x2 grid of orthogonalized VECM impulse responses for the 10-year yield and 3-month T-bill, Cholesky ordering long rate first, showing all four responses converging to nonzero permanent levels with bootstrap confidence bands"><p><em>All four panels converge to nonzero levels, not zero. A long-rate shock settles near +0.33pp in <strong>both</strong> rates; a short-rate shock settles near +0.60pp in both — larger, since <span class="math inline">\(|\hat\alpha_2|&gt;|\hat\alpha_1|\)</span> means the short-rate shock triggers a stronger, faster adjustment. The Cholesky restriction is visible directly: the short rate’s response to a long-rate shock is exactly zero at <span class="math inline">\(h=0\)</span>, then rises gradually.</em></p>
</section>
<section id="why-the-responses-never-return-to-zero" class="slide level2">
<h2>Why the Responses Never Return to Zero</h2>
<div class="eo-recap">
<p><strong>Every shock in a cointegrated system decomposes into two genuinely distinct pieces.</strong> A <strong>permanent</strong> shock moves the common stochastic trend itself — an inflation-expectations or neutral-rate shift that relocates both rates’ long-run level and is never reversed. A <strong>transitory</strong> shock moves the spread away from equilibrium — a flight-to-safety episode compressing the term premium — and the error correction mechanism reverses it over subsequent quarters.</p>
</div>
<p>With <span class="math inline">\(r=1\)</span> in a two-variable system: exactly one permanent shock, one transitory shock — no more, no fewer.</p>
</section>
<section id="reading-inversions-through-this-lens" class="slide level2">
<h2>Reading Inversions Through This Lens</h2>
<blockquote>
<p>An inversion can arise from either type of shock. Does the VECM framework let us tell them apart?</p>
</blockquote>
<div class="eo-recap">
<p><strong>A permanent shock</strong> that raises short rates more than long rates — the Volcker disinflation — produces an inversion that resolves only once <em>both</em> rates settle at their new long-run levels: slow, structural. <strong>A transitory shock</strong> that compresses the spread — a flight-to-quality episode — produces an inversion the ECT reverses more quickly, pulling both rates back toward the existing long-run relationship: faster, mechanical.</p>
</div>
<div class="eo-hazard">
<p><strong>Neither a levels VAR nor a differenced VAR can make this distinction at all.</strong> The permanent/transitory split is available only once the cointegrating structure is made explicit — a capability unique to the VECM among everything built in this course so far.</p>
</div>
</section>
<section id="setting-up-the-definitive-comparison" class="slide level2">
<h2>Setting Up the Definitive Comparison</h2>
<blockquote>
<p>Section 6 already showed the ECT is invisible in short-run residual diagnostics. Where does it actually matter?</p>
</blockquote>
<p>Produce 40-quarter-ahead forecasts from both the VECM and the differenced VAR, starting from the end of the sample (2019 Q4).</p>
<div class="eo-recap">
<p><strong>Short horizons: nearly indistinguishable</strong> — the dominant force at 1-2 quarters ahead is short-run momentum, where both models agree. <strong>Long horizons: they diverge</strong> — the VECM’s error correction term pulls the spread back toward its estimated long-run mean; the differenced VAR has no such mechanism and lets the spread wander freely.</p>
</div>
</section>
<section id="applied-the-forecast-comparison" class="slide level2">
<h2>Applied: The Forecast Comparison</h2>

<img data-src="../../chapters/08/chapter_08_files/figure-html/fig-forecast-comparison-output-1.png" class="img-fluid r-stretch" alt="40-quarter-ahead forecasts for the 10-year yield and 3-month T-bill from the VECM (solid) and differenced VAR (dashed), starting 2019Q4, with the VECM converging to a 1.37 percentage point spread and the differenced VAR to only 0.35"><p><em>VECM: long rate settles near 2.44%, short rate near 1.07% — a long-run spread of <strong>1.37pp</strong>, matching the estimated term premium exactly. Differenced VAR: 1.97% and 1.62% — a spread of only <strong>0.35pp</strong>, implausibly small against sixty-five years of data averaging 1.47pp. The gap is visible from the first forecast quarter and widens continuously.</em></p>
</section>
<section id="the-definitive-verdict" class="slide level2">
<h2>The Definitive Verdict</h2>
<div class="eo-hazard">
<p><strong>The differenced VAR is not a safe fallback — it is the wrong tool for any application where long-horizon forecasts matter.</strong> Pension fund liability matching, monetary policy projections, fixed-income portfolio construction — anywhere a multi-year forecast of the yield curve enters a real decision, ignoring cointegration produces forecasts that violate a relationship sixty-five years of data strongly support.</p>
</div>
<div class="eo-recap">
<p><strong>This is the answer to the question Section 1 opened with.</strong> Neither levels nor differences alone were correct; the VECM is what happens when you refuse both easy answers and build the long-run relationship in explicitly. The cost of getting this wrong is not abstract — it’s a quantified 1.02 percentage point gap in a forecast that compounds for as long as the horizon extends.</p>
</div>
</section>
<section id="recap" class="slide level2 recap-slide" data-background-color="#87A96B" data-footer="false">
<h2>Recap</h2>
<p>We resolved the boundary Chapter 7 left standing. Cointegration formalized the precise condition under which two <span class="math inline">\(I(1)\)</span> series produce a stationary combination — a shared stochastic trend that cancels. The <span class="math inline">\(\Pi\)</span> matrix showed exactly where that information lives inside a VAR, and its rank — tested formally by the Johansen procedure — determined how many such long-run relationships genuinely exist. The VECM reparameterized the system to make short-run dynamics and long-run equilibrium correction two distinct, separately estimable, economically interpretable pieces, validated on the yield curve with coefficients matching the expectations hypothesis almost exactly. Diagnostics confirmed the model was well-specified while revealing an important subtlety: the error correction term is invisible in short-run residuals and decisive only at long horizons — exactly what the closing forecast comparison then quantified precisely.</p>
<div class="eo-recap">
<p>Every tool since Chapter 3 has assumed the innovations <span class="math inline">\(\varepsilon_t\)</span> have constant variance. We have never once tested that assumption directly.</p>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p>Every model since Chapter 3 has carried one further unstated assumption: that the variance of the innovations, <span class="math inline">\(\sigma^2\)</span>, is constant over time. Chapter 1 flagged this in passing — Chapter 3’s white noise discussion noted that squared innovations can be correlated even when the innovations themselves aren’t. We deferred that observation. It’s time to develop it properly.</p>
<p>Chapter 9 builds the <strong>ARCH and GARCH</strong> family — models where the <em>conditional variance itself</em> follows its own dynamic process, capturing the volatility clustering visible in almost every financial return series: calm periods and turbulent periods that persist and cluster together, rather than innovations of constant, unchanging size. This isn’t a minor technical refinement. For risk management, options pricing, and Value-at-Risk, the variance dynamics are often the entire object of interest — not a nuisance to average away, but the very thing being modeled.</p>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<div class="eo-keyterms">
<dl>
<dt>Cointegration</dt>
<dd>
Two or more <span class="math inline">\(I(1)\)</span> series with a stationary linear combination <span class="math inline">\(z_t=y_t-\beta x_t\)</span>; arises when the series share a common stochastic trend that cancels.
</dd>
<dt>Cointegrating vector / Equilibrium residual</dt>
<dd>
<span class="math inline">\((1,-\beta)'\)</span>, normalized on the first variable; <span class="math inline">\(z_t\)</span> measures the current deviation from the long-run relationship.
</dd>
<dt>Cointegrating rank <span class="math inline">\(r\)</span></dt>
<dd>
The number of independent cointegrating vectors among <span class="math inline">\(n\)</span> <span class="math inline">\(I(1)\)</span> variables, <span class="math inline">\(0\leq r\leq n-1\)</span>; determines whether a differenced VAR (<span class="math inline">\(r=0\)</span>) or a VECM (<span class="math inline">\(0&lt;r&lt;n\)</span>) is correct.
</dd>
<dt>Common trends representation</dt>
<dd>
<span class="math inline">\(\mathbf{y}_t=\boldsymbol\Gamma\mathbf{f}_t+\boldsymbol\xi_t\)</span> (Stock-Watson); <span class="math inline">\(n-r\)</span> genuinely shared stochastic trends underlie <span class="math inline">\(n\)</span> variables when cointegrating rank is <span class="math inline">\(r\)</span>.
</dd>
<dt><span class="math inline">\(\boldsymbol\Pi\)</span> matrix / Reduced rank</dt>
<dd>
<span class="math inline">\(\boldsymbol\Pi=\sum_i\mathbf{A}_i-\mathbf{I}_n\)</span> in the VECM representation; <span class="math inline">\(\text{rank}(\boldsymbol\Pi)=r\)</span> factors as <span class="math inline">\(\boldsymbol\alpha\boldsymbol\beta'\)</span>, encoding all long-run information in the system.
</dd>
<dt>Johansen trace test / Maximum eigenvalue test</dt>
<dd>
Sequential tests on the eigenvalues of a reduced-rank regression, determining cointegrating rank; non-standard critical values due to the same Davies-type problem as QLR.
</dd>
<dt>Vector error correction model (VECM)</dt>
<dd>
<span class="math inline">\(\Delta\mathbf{y}_t=\mathbf{c}+\boldsymbol\alpha\boldsymbol\beta'\mathbf{y}_{t-1}+\sum_i\boldsymbol\Gamma_i\Delta\mathbf{y}_{t-i}+\mathbf{u}_t\)</span>; separates short-run dynamics from long-run equilibrium correction explicitly.
</dd>
<dt>Speed of adjustment <span class="math inline">\(\boldsymbol\alpha\)</span></dt>
<dd>
How strongly each variable responds to last period’s deviation from long-run equilibrium; zero for a weakly exogenous variable.
</dd>
<dt>Weak exogeneity</dt>
<dd>
A variable with <span class="math inline">\(\alpha_i=0\)</span> — it enters the cointegrating relationship but bears none of the adjustment burden.
</dd>
<dt>Permanent shock / Transitory shock</dt>
<dd>
A shock to the common stochastic trend (never reversed) vs.&nbsp;a shock to the equilibrium spread (reversed by error correction); together explain why VECM impulse responses converge to nonzero levels.
</dd>
<dt>Spurious cointegration</dt>
<dd>
A significant Johansen trace statistic despite no genuine cointegration — a risk especially acute with weak theoretical priors, small samples, or undetected structural breaks.
</dd>
</dl>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ECON-5371 · Time Series Analysis and Forecasting</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="08_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="08_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="08_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="08_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="08_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="08_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="08_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="08_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="08_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="08_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>