<!DOCTYPE html>
<html lang="en"><head>
<script src="10_files/libs/clipboard/clipboard.min.js"></script>
<script src="10_files/libs/quarto-html/tabby.min.js"></script>
<script src="10_files/libs/quarto-html/popper.min.js"></script>
<script src="10_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="10_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="10_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Nicolas Cachanosky, Department of Economics and Finance">
  <meta name="dcterms.date" content="2026-08-31">
  <title>Regime-Switching Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="10_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="10_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="10_files/libs/revealjs/dist/theme/quarto-8918f2d902338036edb16d438b2b49f4.css">
  <link rel="stylesheet" href="../slides-extra.css">
  <link href="10_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="10_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="10_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="10_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#36454F" data-footer="" class="quarto-title-block">
  <h1 class="title">Regime-Switching Models</h1>
  <p class="subtitle">Chapter 10</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Nicolas Cachanosky, Department of Economics and Finance 
</div>
</div>
</div>

  <p class="date">2026-08-31</p>
</section>
<section id="one-assumption-nine-chapters-deep" class="slide level2">
<h2>One Assumption, Nine Chapters Deep</h2>
<blockquote>
<p>The ARMA coefficients from Chapter 3. The GARCH dynamics from Chapter 9. The VAR coefficients from Chapter 7. What do all of them silently share?</p>
</blockquote>
<ul>
<li>Every one was estimated <strong>once</strong> and applied uniformly across the entire sample</li>
<li>Same mean, same persistence, same volatility structure — in 1955 Q1 as in 2009 Q1</li>
<li>A convenient assumption. Not obviously a true one.</li>
</ul>
<div class="eo-recap">
<p>This chapter relaxes that assumption in the most disciplined way available. Not letting parameters drift continuously — allowing them to take one of a <strong>small number of discrete values</strong>, switching between them according to a hidden Markov chain. The economy is always in one state or another; which state, at any given quarter, is unobserved and must be inferred probabilistically.</p>
</div>
<aside class="notes">
<p>Open here. Frame this as the natural generalization of Chapter 6’s one-time structural break — Chapter 6 flagged Markov-switching as the recurring generalization; this chapter delivers on that promise. ~2 min.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-this-chapter-matters" class="slide level2">
<h2>Why This Chapter Matters</h2>
<p>One model, one algorithm, two complementary extensions:</p>
<ol type="1">
<li><strong>The two-state Markov-switching model</strong> — regimes, transition probabilities, the ergodic distribution</li>
<li><strong>The Hamilton filter</strong> — the recursive algorithm that infers which regime we’re likely in, given only what’s been observed so far</li>
<li><strong>Threshold models</strong> — the complementary family where the switching variable is <em>observed</em>, not hidden</li>
<li><strong>MS-VAR</strong> — a brief map of the multivariate extension</li>
</ol>
<div class="eo-recap">
<p>Running example: <strong>US real GDP growth</strong>, continued from Chapter 4 — this time asking not “what’s the best ARIMA fit” but “does growth behave like one process, or two?”</p>
</div>
</section>
<section id="todays-roadmap" class="slide level2 outline-slide">
<h2>Today’s Roadmap</h2>
<ol type="1">
<li>Why parameters might switch</li>
<li>The two-state Markov-switching model</li>
<li>The Hamilton filter</li>
<li>Estimation and empirical results</li>
<li>Threshold models: a brief tour</li>
<li>MS-VAR: a brief map</li>
</ol>
</section>
<section id="why-parameters-might-switch" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Why Parameters Might Switch</h2>
<div class="eo-section-label">
<p>Section 1</p>
</div>
</section>
<section id="what-chapter-4s-arima-assumed" class="slide level2">
<h2>What Chapter 4’s ARIMA Assumed</h2>
<blockquote>
<p>Chapter 4 asked: given the history of GDP growth up to today, what’s the best prediction for next quarter? Where did that answer come from?</p>
</blockquote>
<p>A single estimated equation whose coefficients were <strong>fixed for the entire postwar sample</strong> — the same mean, the same persistence, the same variance in 1955 Q1 as in 2009 Q1.</p>
<div class="eo-recap">
<p>Convenient. Not obviously true. NBER recession dating — a broad reading of macroeconomic activity — already tells us the economy moves through qualitatively distinct phases. Does GDP growth’s own statistical behavior confirm that, or is it an artifact of how recessions happen to get labeled?</p>
</div>
</section>
<section id="seeing-two-different-processes-at-once" class="slide level2">
<h2>Seeing Two Different Processes at Once</h2>

<img data-src="../../chapters/10/chapter_10_files/figure-html/fig-gdp-growth-output-1.png" class="img-fluid r-stretch" alt="Annualized quarterly real GDP growth, 1947-2019, NBER recessions shaded, showing growth clustering around a positive mean outside recessions and turning sharply negative with higher volatility during them"><p><em>Outside the shaded recessions: growth positive, moderately persistent, clustered around a stable trend. Inside them: growth turns sharply negative, volatility increases, the series behaves like a genuinely different data-generating process.</em></p>
<div class="eo-hazard">
<p><strong>A single linear model treats every observation as a draw from the same distribution</strong> — a restriction this figure directly challenges. Whether that restriction is costly enough to abandon is what the rest of the chapter tests formally.</p>
</div>
</section>
<section id="the-distributional-signature" class="slide level2">
<h2>The Distributional Signature</h2>
<blockquote>
<p>If GDP growth really were one process throughout, its unconditional distribution should look like a single bell curve. Does it?</p>
</blockquote>
<div class="eo-recap">
<p><strong>No — and the deviations from normality cluster precisely around NBER recessions.</strong> A histogram of quarterly growth shows a heavier left tail and excess kurtosis relative to a single Gaussian fit — exactly the signature two overlapping distributions with different means would produce, mixed together. This is the same kind of evidence Chapter 9’s ARCH-LM test formalized for volatility clustering — here, applied to the possibility of switching means instead of switching variances.</p>
</div>
</section>
<section id="from-description-to-a-formal-model" class="slide level2">
<h2>From Description to a Formal Model</h2>
<blockquote>
<p>Chapter 6 gave us formal tools for a <strong>one-time</strong> structural break — Chow, QLR, Bai-Perron. GDP growth doesn’t look like it broke once and stayed changed; it looks like it moves back and forth between two states repeatedly, across the whole postwar sample.</p>
</blockquote>
<div class="eo-recap">
<p><strong>This is exactly the recurring generalization Chapter 6 flagged and deferred.</strong> A structural break model asks “did the process change, once, at some date <span class="math inline">\(\tau\)</span>?” A regime-switching model asks “which of <span class="math inline">\(M\)</span> states is the process in <em>right now</em>, understanding that it may have switched before and will switch again?” Same underlying concern — parameter instability — genuinely different mathematical machinery.</p>
</div>
<p>The next section builds that machinery from first principles.</p>
</section>
<section id="the-two-state-markov-switching-model" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The Two-State Markov-Switching Model</h2>
<div class="eo-section-label">
<p>Section 2</p>
</div>
</section>
<section id="the-transition-probability-matrix" class="slide level2">
<h2>The Transition Probability Matrix</h2>
<div class="eo-definition">
<p><strong>Two-state first-order Markov chain.</strong> <span class="math inline">\(s_t\in\{0,1\}\)</span>: expansion, recession. The chain is memoryless — tomorrow’s regime depends only on today’s, not on the full history:</p>
<p><span class="math display">\[
P = \begin{pmatrix}p_{00}&amp;p_{01}\\p_{10}&amp;p_{11}\end{pmatrix}, \qquad p_{ij}=\Pr(s_t=j\mid s_{t-1}=i)
\]</span></p>
<p>Each row sums to 1: <span class="math inline">\(p_{00}+p_{01}=1\)</span>, <span class="math inline">\(p_{10}+p_{11}=1\)</span> — only two free parameters, <span class="math inline">\(p_{00}\)</span> and <span class="math inline">\(p_{11}\)</span>.</p>
</div>
<p><span class="math inline">\(p_{00}\)</span> near 1: expansions persist. <span class="math inline">\(p_{11}\)</span> near 1: recessions persist. Neither is fixed by assumption — both are estimated from the data.</p>
</section>
<section id="expected-regime-duration" class="slide level2">
<h2>Expected Regime Duration</h2>
<blockquote>
<p>If <span class="math inline">\(p_{00}=0.94\)</span>, how many quarters does an expansion last on average, before switching?</p>
</blockquote>
<div class="eo-recap">
<p><strong>A geometric distribution.</strong> Staying in state <span class="math inline">\(i\)</span> for exactly <span class="math inline">\(k\)</span> periods requires <span class="math inline">\(k-1\)</span> successive “stay” draws, then one “leave” — probability <span class="math inline">\(p_{ii}^{k-1}(1-p_{ii})\)</span>. The expected duration:</p>
<p><span class="math display">\[
\mathbb{E}[\text{duration in state }i] = \frac{1}{1-p_{ii}}
\]</span></p>
</div>
<p>At <span class="math inline">\(p_{00}=0.94\)</span>: expected expansion length <span class="math inline">\(=1/0.06\approx16.7\)</span> quarters, over 4 years. At <span class="math inline">\(p_{11}=0.75\)</span>: expected recession length <span class="math inline">\(=1/0.25=4\)</span> quarters, exactly one year. Both broadly match postwar NBER cycle chronology.</p>
</section>
<section id="the-ergodic-distribution" class="slide level2">
<h2>The Ergodic Distribution</h2>
<blockquote>
<p>Over a very long sample, what fraction of quarters does the economy spend in each regime — independent of where it started?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Ergodic distribution.</strong> The fixed point <span class="math inline">\(\boldsymbol\pi=P'\boldsymbol\pi\)</span>, <span class="math inline">\(\sum_i\pi_i=1\)</span>. For the two-state case:</p>
<p><span class="math display">\[
\pi_0 = \frac{1-p_{11}}{(1-p_{00})+(1-p_{11})}, \qquad \pi_1=1-\pi_0
\]</span></p>
</div>
<p><span class="math inline">\(\pi_0\)</span> depends <strong>only</strong> on the two transition probabilities — nothing about GDP growth’s actual values enters this calculation at all.</p>
</section>
<section id="working-the-numbers" class="slide level2">
<h2>Working the Numbers</h2>
<p><span class="math inline">\(p_{00}=0.94\)</span>, <span class="math inline">\(p_{11}=0.75\)</span>:</p>
<p><span class="math display">\[
\pi_0 = \frac{1-0.75}{(1-0.94)+(1-0.75)} = \frac{0.25}{0.06+0.25} = \frac{0.25}{0.31} \approx 0.81
\]</span></p>
<div class="eo-recap">
<p><strong>The economy spends 81% of its time in expansion, 19% in recession — consistent with NBER’s own classification of roughly 15-20% of postwar quarters as recessionary.</strong> This number falls entirely out of the transition matrix; it’s a check on internal consistency, not yet a claim about GDP growth itself.</p>
</div>
</section>
<section id="the-ms-ark-model" class="slide level2">
<h2>The MS-AR(<span class="math inline">\(k\)</span>) Model</h2>
<p>With the Markov chain in place, write the model for GDP growth itself:</p>
<div class="eo-definition">
<p><strong>Markov-switching autoregression of order <span class="math inline">\(k\)</span>.</strong></p>
<p><span class="math display">\[
y_t = \mu_{s_t}+\sum_{j=1}^k\phi_j(y_{t-j}-\mu_{s_{t-j}})+\varepsilon_t, \qquad \varepsilon_t\sim N(0,\sigma_{s_t}^2)
\]</span></p>
<p><span class="math inline">\(\mu_m,\sigma_m^2\)</span>: regime-specific. <span class="math inline">\(\phi_j\)</span>: shared across regimes. Full parameter vector: <span class="math inline">\(\theta=(\mu_0,\mu_1,\sigma_0^2,\sigma_1^2,\phi_1,\ldots,\phi_k,p_{00},p_{11})\)</span>.</p>
</div>
</section>
<section id="why-this-model-is-genuinely-nonlinear" class="slide level2">
<h2>Why This Model Is Genuinely Nonlinear</h2>
<blockquote>
<p>The AR correction term is <span class="math inline">\(\mu_{s_{t-j}}\)</span> — the regime-specific mean at time <span class="math inline">\(t-j\)</span>, not time <span class="math inline">\(t\)</span>. Why does that make estimation harder than an ordinary ARMA?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>Conditioning on today’s regime alone isn’t enough — the correction depends on which regime applied at <em>every</em> past lag, and those were themselves unobserved.</strong> To evaluate the likelihood at time <span class="math inline">\(t\)</span>, we must sum over every possible combination of past regimes consistent with the current one. This isn’t a minor computational inconvenience; it’s exactly what the Hamilton filter, Section 3’s subject, is built to handle efficiently.</p>
</div>
</section>
<section id="mean-switching-vs.-variance-switching-vs.-both" class="slide level2">
<h2>Mean-Switching vs.&nbsp;Variance-Switching vs.&nbsp;Both</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Specification</th>
<th style="text-align: center;">Mean switches</th>
<th style="text-align: center;">Variance switches</th>
<th style="text-align: center;">Extra params</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean-switching only</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;"><span class="math inline">\(\mu_0,\mu_1,\sigma^2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Variance-switching only</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;"><span class="math inline">\(\mu,\sigma_0^2,\sigma_1^2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Both</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;"><span class="math inline">\(\mu_0,\mu_1,\sigma_0^2,\sigma_1^2\)</span></td>
</tr>
</tbody>
</table>
<div class="eo-recap">
<p><strong>For GDP growth, the case for mean-switching is clear and strong.</strong> The gap between expansion mean (3.71%) and recession mean (<span class="math inline">\(-1.41\)</span>%) — 5.1 percentage points — is the dominant feature of the data. Regime-specific standard deviations are nearly <strong>identical</strong> across the two NBER-classified phases: variance switching adds little real signal here, and actively creates an estimation problem — the likelihood surface develops a variance-only local optimum that’s numerically easier to find than the genuine mean-switching solution.</p>
</div>
<div class="eo-hazard">
<p><strong>The working model for this chapter: mean-switching MS-AR(2), common variance</strong> — following Hamilton (1989) exactly. Not a simplification of convenience; the data themselves argue for it. Section 4 revisits variance-switching as a deliberate modeling choice, not a default.</p>
</div>
</section>
<section id="the-hamilton-filter" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>The Hamilton Filter</h2>
<div class="eo-section-label">
<p>Section 3</p>
</div>
</section>
<section id="the-inference-problem" class="slide level2">
<h2>The Inference Problem</h2>
<blockquote>
<p>Given everything observed through today, what’s the probability the economy is currently in each regime?</p>
</blockquote>
<p><span class="math display">\[
\Pr(s_t=j\mid y_1,\ldots,y_t), \qquad j\in\{0,1\}
\]</span></p>
<div class="eo-recap">
<p><strong>A filtering problem</strong> — <span class="math inline">\(s_t\)</span> is hidden; the observations carry information about it. The <strong>Hamilton filter</strong> extracts that information recursively, one observation at a time, left to right through the sample. Two objects at each date: <strong>filtered probabilities</strong> <span class="math inline">\(\xi_{t|t}\)</span> (using data through <span class="math inline">\(t\)</span>) and <strong>predicted probabilities</strong> <span class="math inline">\(\xi_{t|t-1}\)</span> (before observing <span class="math inline">\(y_t\)</span>) — the one-step-ahead regime forecast.</p>
</div>
</section>
<section id="step-1-prediction" class="slide level2">
<h2>Step 1: Prediction</h2>
<p><span class="math display">\[
\xi_{t|t-1} = P'\xi_{t-1|t-1}
\]</span></p>
<p>Written out for the two-state case:</p>
<p><span class="math display">\[
\Pr(s_t=0\mid\mathcal{F}_{t-1}) = p_{00}\Pr(s_{t-1}=0\mid\mathcal{F}_{t-1})+p_{01}\Pr(s_{t-1}=1\mid\mathcal{F}_{t-1})
\]</span></p>
<div class="eo-recap">
<p><strong>In words</strong>: the predicted probability of expansion tomorrow is “probability of expansion today and staying” plus “probability of recession today and switching.” No observation of <span class="math inline">\(y_t\)</span> has entered yet — pure projection through the transition matrix.</p>
</div>
</section>
<section id="step-2-update" class="slide level2">
<h2>Step 2: Update</h2>
<p>When <span class="math inline">\(y_t\)</span> arrives, revise the prediction via Bayes’ rule:</p>
<p><span class="math display">\[
f(y_t\mid s_t=j,\mathcal{F}_{t-1}) = \frac{1}{\sqrt{2\pi\sigma_j^2}}\exp\left(-\frac{(y_t-\mu_j^*)^2}{2\sigma_j^2}\right)
\]</span></p>
<p><span class="math display">\[
\Pr(s_t=j\mid\mathcal{F}_t) = \frac{f(y_t\mid s_t=j,\mathcal{F}_{t-1})\cdot\Pr(s_t=j\mid\mathcal{F}_{t-1})}{\sum_mf(y_t\mid s_t=m,\mathcal{F}_{t-1})\cdot\Pr(s_t=m\mid\mathcal{F}_{t-1})}
\]</span></p>
<div class="eo-recap">
<p><strong>Updated probability <span class="math inline">\(\propto\)</span> likelihood <span class="math inline">\(\times\)</span> prior.</strong> The denominator normalizes to sum to one — and is itself the marginal density of <span class="math inline">\(y_t\)</span> given the past, summed across <span class="math inline">\(t\)</span> to build the log-likelihood used for estimation in Section 4.</p>
</div>
</section>
<section id="the-filter-assembled" class="slide level2">
<h2>The Filter, Assembled</h2>
<div class="eo-definition">
<p><strong>The Hamilton filter.</strong> Given initial <span class="math inline">\(\xi_{1|0}\)</span> (typically the ergodic distribution), iterate for <span class="math inline">\(t=1,\ldots,T\)</span>:</p>
<ol type="1">
<li><strong>Predict</strong>: <span class="math inline">\(\xi_{t|t-1}=P'\xi_{t-1|t-1}\)</span></li>
<li><strong>Evaluate</strong>: <span class="math inline">\(\eta_t=(f(y_t\mid s_t=0,\mathcal{F}_{t-1}),f(y_t\mid s_t=1,\mathcal{F}_{t-1}))'\)</span></li>
<li><strong>Update</strong>: <span class="math inline">\(\xi_{t|t}=(\eta_t\odot\xi_{t|t-1})/(\mathbf{1}'(\eta_t\odot\xi_{t|t-1}))\)</span></li>
</ol>
</div>
<p>Predict, then correct with new data — the same two-step logic underlying every recursive filter in this course, now applied to a discrete hidden state.</p>
</section>
<section id="working-an-example-setting-up" class="slide level2">
<h2>Working an Example: Setting Up</h2>
<p><span class="math inline">\(\mu_0=3\)</span>, <span class="math inline">\(\mu_1=-2\)</span>, <span class="math inline">\(\sigma^2=4\)</span>, <span class="math inline">\(p_{00}=0.9\)</span>, <span class="math inline">\(p_{11}=0.7\)</span>. Ergodic initialization: <span class="math inline">\(\pi_0=0.75\)</span>, <span class="math inline">\(\pi_1=0.25\)</span>.</p>
<p><strong>Period <span class="math inline">\(t=1\)</span></strong>: <span class="math inline">\(y_1=4.2\)</span> — a strong expansion quarter.</p>
<p><span class="math display">\[
f(y_1\mid s_1=0)=\phi\left(\frac{4.2-3}{2}\right)=\phi(0.60)\approx0.333, \qquad f(y_1\mid s_1=1)=\phi\left(\frac{4.2+2}{2}\right)=\phi(3.10)\approx0.003
\]</span></p>
<p><span class="math display">\[
\Pr(s_1=0\mid y_1) = \frac{0.333\times0.75}{0.333\times0.75+0.003\times0.25} = \frac{0.250}{0.251}\approx0.996
\]</span></p>
<div class="eo-recap">
<p><strong>A single quarter of strong growth pushes the expansion probability to 99.6%.</strong> The observation was overwhelmingly more consistent with one regime than the other — the filter reflects that decisively.</p>
</div>
</section>
<section id="working-the-example-a-sharp-reversal" class="slide level2">
<h2>Working the Example: A Sharp Reversal</h2>
<p><strong>Period <span class="math inline">\(t=2\)</span></strong>: predict forward first, then <span class="math inline">\(y_2=-3.8\)</span> arrives — a sharp contraction.</p>
<p><span class="math display">\[
\Pr(s_2=0\mid y_1) = 0.9(0.996)+0.3(0.004)\approx0.897
\]</span></p>
<p>Even before seeing <span class="math inline">\(y_2\)</span>, expansion’s high persistence keeps the predicted probability at 89.7%. Then:</p>
<p><span class="math display">\[
f(y_2\mid s_2=0)=\phi(-3.40)\approx0.001, \qquad f(y_2\mid s_2=1)=\phi(-0.90)\approx0.266
\]</span></p>
<p><span class="math display">\[
\Pr(s_2=0\mid y_1,y_2) = \frac{0.001\times0.897}{0.001\times0.897+0.266\times0.103} \approx0.032
\]</span></p>
<div class="eo-recap">
<p><strong>One quarter of sharply negative growth drives the expansion probability from 89.7% to 3.2%.</strong> This is the filter’s real character: high persistence keeps predictions sticky, but a sufficiently informative observation can override that persistence almost entirely, in a single step.</p>
</div>
</section>
<section id="filtered-vs.-smoothed-probabilities" class="slide level2">
<h2>Filtered vs.&nbsp;Smoothed Probabilities</h2>
<div class="eo-recap">
<p><strong>Filtered</strong> <span class="math inline">\(\xi_{t|t}\)</span>: real-time, causal — uses only data through <span class="math inline">\(t\)</span>, exactly what a forecaster could have computed <em>at the time</em>. <strong>Smoothed</strong> <span class="math inline">\(\xi_{t|T}\)</span>: uses the <em>entire</em> sample, running the filter forward then a backward pass (the Kim, 1994 smoother) that propagates later evidence back through the transition structure.</p>
</div>
<div class="eo-hazard">
<p><strong>Which to use is not a matter of taste.</strong> Real-time forecasting evaluation: filtered probabilities, or risk look-ahead bias — exactly Chapter 5’s warning, now in a new setting. Historical classification against NBER dates: smoothed probabilities, since NBER’s own dating is itself retrospective. Using the wrong one for the task at hand quietly contaminates the comparison.</p>
</div>
</section>
<section id="the-bridge-to-chapter-11" class="slide level2">
<h2>The Bridge to Chapter 11</h2>
<blockquote>
<p>Prior, likelihood, posterior, forward projection — every piece of the Hamilton filter has a direct counterpart somewhere else in statistics. Where?</p>
</blockquote>
<div class="eo-recap">
<p><strong>The Kalman filter, Chapter 11, solves the identical problem for a continuous hidden state.</strong> Same prediction-correction logic throughout. The only real difference: here, the state is discrete — the prior/posterior are probability <em>vectors</em>, and the “densities” are Gaussian mixtures. There, the state is continuous and Gaussian — the prior/posterior are a mean vector and covariance matrix, and the updates are linear. The Kalman filter is, in a precise sense, the Gaussian-state analogue of exactly this algorithm.</p>
</div>
<p>Nothing in Chapter 11 will feel genuinely unfamiliar — the architecture is already built.</p>
</section>
<section id="estimation-and-empirical-results" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Estimation and Empirical Results</h2>
<div class="eo-section-label">
<p>Section 4</p>
</div>
</section>
<section id="maximum-likelihood-via-the-filter" class="slide level2">
<h2>Maximum Likelihood via the Filter</h2>
<p>The Hamilton filter delivers more than regime probabilities — the normalizing constant at each update step <strong>is</strong> the marginal density of <span class="math inline">\(y_t\)</span> given the past:</p>
<p><span class="math display">\[
\ell(\theta) = \sum_{t=1}^T\log f(y_t\mid\mathcal{F}_{t-1};\theta)
\]</span></p>
<div class="eo-recap">
<p><strong>MLE maximizes <span class="math inline">\(\ell(\theta)\)</span> over <span class="math inline">\(\theta=(\mu_0,\mu_1,\sigma_0^2,\sigma_1^2,\phi_1,\phi_2,p_{00},p_{11})\)</span>.</strong> Each evaluation requires running the <strong>full filter</strong> — <span class="math inline">\(T\)</span> prediction-update cycles — genuinely more expensive than OLS, but entirely tractable at typical macroeconomic sample sizes.</p>
</div>
</section>
<section id="a-genuine-identification-problem-labelling" class="slide level2">
<h2>A Genuine Identification Problem: Labelling</h2>
<blockquote>
<p>Swap every regime-0 parameter with regime-1, and every regime-1 with regime-0. What happens to the likelihood?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>Nothing — it’s exactly unchanged.</strong> The regimes are interchangeable in the likelihood itself; the surface has two symmetric solutions, and an unguided optimizer can converge to either. Left unresolved, <code>statsmodels</code> can settle on a <strong>variance-only split</strong> — two clusters both centered near positive growth, distinguished only by dispersion — rather than the economically meaningful expansion/contraction separation.</p>
</div>
<div class="eo-recap">
<p><strong>The fix: supply starting values encoding the economic prior directly</strong> — a positive mean near trend growth for expansion, a negative mean for recession. Then verify after estimation: regime 0 should have the higher mean, and the implied ergodic recession share should be plausible (roughly 10-20% for postwar US data).</p>
</div>
</section>
<section id="applied-the-fitted-ms-ar2" class="slide level2">
<h2>Applied: The Fitted MS-AR(2)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Expansion</th>
<th style="text-align: center;">Recession</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean <span class="math inline">\(\hat\mu\)</span></td>
<td style="text-align: center;"><span class="math inline">\(3.66^{***}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-3.85^{***}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Std. dev. <span class="math inline">\(\hat\sigma\)</span></td>
<td style="text-align: center;">2.95 (common)</td>
<td style="text-align: center;">2.95 (common)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p_{ii}\)</span> (persistence)</td>
<td style="text-align: center;">0.956</td>
<td style="text-align: center;">0.400</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\hat\phi_1=0.338^{***}\)</span>, <span class="math inline">\(\hat\phi_2=0.154^{***}\)</span> — both significant, capturing the modest positive serial correlation Chapter 4’s ARIMA also found.</p>
<div class="eo-recap">
<p><strong>The estimated mean gap — 7.5pp — is wider than the raw NBER-classified gap (5.1pp).</strong> The model assigns recession quarters more decisively than NBER dates spread across a full quarter of transition. Everything else lines up closely with Section 1’s descriptive statistics.</p>
</div>
</section>
<section id="reading-the-persistence-an-honest-puzzle" class="slide level2">
<h2>Reading the Persistence: An Honest Puzzle</h2>
<blockquote>
<p><span class="math inline">\(\hat p_{00}=0.956\)</span> implies expansions last 22.7 quarters — 5.7 years, very plausible. <span class="math inline">\(\hat p_{11}=0.400\)</span> implies recessions last <strong>1.7 quarters</strong> — shorter than any NBER recession on record. What’s going on?</p>
</blockquote>
<div class="eo-hazard">
<p><strong>The mean-switching specification identifies “recession” as individual sharply-negative observations, not sustained contractions.</strong> Each deep-negative quarter looks, to the likelihood, like an independent visit to the recession regime — producing a high exit probability even though actual recessions last several quarters. The 6.8% ergodic recession share is plausible (close to NBER’s 11.7%), but achieved through many brief visits rather than fewer sustained ones.</p>
</div>
<div class="eo-recap">
<p><strong>A known limitation of this specification, not an error.</strong> Allowing AR dynamics or variance to switch as well could produce more realistic durations — at the cost of the estimation difficulties Section 2 already flagged.</p>
</div>
</section>
<section id="seeing-the-two-distributions" class="slide level2">
<h2>Seeing the Two Distributions</h2>

<img data-src="../../chapters/10/chapter_10_files/figure-html/fig-regime-densities-output-1.png" class="img-fluid r-stretch" alt="GDP growth histogram overlaid with the two estimated MS-AR(2) regime-conditional normal distributions, expansion centered near 3.66 percent and recession near -3.85 percent, sharing a common standard deviation"><p><em>Expansion (sky blue, <span class="math inline">\(\hat\mu=3.66\)</span>) and recession (terracotta, <span class="math inline">\(\hat\mu=-3.85\)</span>) share the common <span class="math inline">\(\hat\sigma=2.95\)</span>. The two distributions overlap substantially between <span class="math inline">\(-2\%\)</span> and <span class="math inline">\(2\%\)</span> — exactly why <strong>mild</strong> negative quarters generate only moderate recession probabilities. Below <span class="math inline">\(-4\%\)</span>: unambiguously recession. Above <span class="math inline">\(5\%\)</span>: unambiguously expansion.</em></p>
</section>
<section id="the-real-test-recovering-nber-without-being-told" class="slide level2">
<h2>The Real Test: Recovering NBER Without Being Told</h2>
<blockquote>
<p>The model never sees NBER dates during estimation — only GDP growth itself. If smoothed probabilities align with recession shading anyway, that’s genuine evidence the two-state structure captures something real.</p>
</blockquote>

<img data-src="../../chapters/10/chapter_10_files/figure-html/fig-smoothed-probs-output-1.png" class="img-fluid r-stretch" alt="Smoothed recession probability from MS-AR(2), 1947-2019, with NBER recessions shaded, showing the model firing clearly on 1960-61, 1973-75, 1981-82, and 2008-09, but largely missing 1990-91 and 2001"><p><em>Fires clearly on 1960-61 (probability reaching 1.0), 1973-75, 1981-82, and the 2008-09 GFC (near 0.9). Response but no sustained signal for 1980.</em></p>
<div class="eo-hazard">
<p><strong>1990-91 and 2001 are largely missed</strong> — both mild by historical standards, no quarters of sharply negative growth. <strong>An honest limitation</strong>: the model recovers recessions defined by <em>deep</em> contractions and misses mild growth slowdowns entirely, exactly what a mean-switching specification with wide overlapping distributions would predict.</p>
</div>
</section>
<section id="the-definitive-test-does-it-forecast-better" class="slide level2">
<h2>The Definitive Test: Does It Forecast Better?</h2>
<blockquote>
<p>Everything so far describes the past well. Does regime-switching actually improve <em>forecasts</em>, the way Chapter 5’s framework demands we ask?</p>
</blockquote>
<p>Same design as Chapter 5: rolling window, fixed evaluation period, one-step-ahead MSFE.</p>
<div class="eo-hazard">
<p><strong>It doesn’t — over this evaluation window.</strong> ARIMA(2,0,0): MSFE 4.383, MAE 1.542. MS-AR(2): MSFE 4.422, MAE 1.547. The regime-switching model does <strong>not</strong> outperform the linear benchmark out of sample.</p>
</div>
</section>
<section id="why-the-honest-answer-is-instructive-not-discouraging" class="slide level2">
<h2>Why the Honest Answer Is Instructive, Not Discouraging</h2>
<div class="eo-recap">
<p><strong>The evaluation window (1985-2019) covers the Great Moderation</strong> — Chapter 6’s own running example — an era of unusually stable growth with only two mild recessions (1990-91, 2001), both of which the smoothed-probability figure just showed the model <strong>largely misses</strong>. The MS-AR’s comparative advantage is detecting <em>sharp</em> contractions — precisely the type this particular window contains too few of to overcome ARIMA’s parsimony advantage.</p>
</div>
<p>A window including the 1970s and early 1980s — genuinely deep recessions, exactly what the model <em>does</em> recover well — would almost certainly reverse this ranking. <strong>The out-of-sample test isn’t a verdict against Markov-switching in general; it’s a verdict about this model on this specific, unusually calm evaluation period.</strong></p>
</section>
<section id="threshold-models-a-brief-tour" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>Threshold Models: A Brief Tour</h2>
<div class="eo-section-label">
<p>Section 5</p>
</div>
</section>
<section id="the-one-distinction-that-matters" class="slide level2">
<h2>The One Distinction That Matters</h2>
<blockquote>
<p>Every model so far assumed the regime <span class="math inline">\(s_t\)</span> is genuinely hidden — inferred, never observed. Is that the only way to build a regime-switching model?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Markov-switching</strong>: regime <span class="math inline">\(s_t\)</span> is latent, governed by transition probabilities <span class="math inline">\(p_{ij}\)</span>; we infer it, never observe it directly.</p>
<p><strong>Threshold models</strong>: the regime is determined by whether an <strong>observable</strong> variable <span class="math inline">\(q_t\)</span> — the threshold variable — sits above or below a threshold <span class="math inline">\(\gamma\)</span>. We know the regime immediately, once <span class="math inline">\(\gamma\)</span> is estimated.</p>
</div>
<div class="eo-recap">
<p><strong>When each is the right tool.</strong> Markov-switching fits better when the driving force is genuinely latent — sentiment, financial stress. Threshold models fit naturally when a specific observable is the plausible trigger — the unemployment rate rising vs.&nbsp;falling, an asset price crossing a known support level.</p>
</div>
</section>
<section id="setar-the-series-determines-its-own-regime" class="slide level2">
<h2>SETAR: The Series Determines Its Own Regime</h2>
<div class="eo-definition">
<p><strong>Threshold autoregression (TAR).</strong> AR coefficients switch depending on whether <span class="math inline">\(y_{t-d}\)</span> crosses a threshold <span class="math inline">\(\gamma\)</span>:</p>
<p><span class="math display">\[
y_t = \begin{cases}\phi_{1,0}+\phi_{1,1}y_{t-1}+\cdots+\varepsilon_t &amp; y_{t-d}\leq\gamma \\ \phi_{2,0}+\phi_{2,1}y_{t-1}+\cdots+\varepsilon_t &amp; y_{t-d}&gt;\gamma\end{cases}
\]</span></p>
<p><strong>Self-exciting TAR (SETAR)</strong>: the threshold variable is a lag of <span class="math inline">\(y_t\)</span> itself — the process determines its own regime.</p>
</div>
<p>Applied to GDP growth with <span class="math inline">\(d=1\)</span>: do dynamics differ depending on whether last quarter’s growth was negative or positive — a natural formalization of asymmetric business-cycle propagation, with no hidden state to estimate.</p>
</section>
<section id="estimating-a-setar" class="slide level2">
<h2>Estimating a SETAR</h2>
<div class="eo-recap">
<p><strong>Conditional least squares.</strong> For any candidate <span class="math inline">\(\gamma\)</span>: split the sample by <span class="math inline">\(y_{t-d}\leq\gamma\)</span> or not, estimate two separate AR regressions by OLS, collect the SSR. <span class="math inline">\(\hat\gamma\)</span> minimizes total SSR across a grid of candidates — no numerical likelihood optimization required, unlike the Hamilton filter.</p>
</div>
<div class="eo-hazard">
<p><span class="math inline">\(\hat\gamma\)</span> has a non-standard limiting distribution — Hansen (1997) provides the asymptotic theory and a bootstrap procedure for its confidence interval.</p>
</div>
</section>
<section id="applied-unemployments-rising-vs.-falling-asymmetry" class="slide level2">
<h2>Applied: Unemployment’s Rising vs.&nbsp;Falling Asymmetry</h2>

<img data-src="../../chapters/10/chapter_10_files/figure-html/fig-threshold-scatter-output-1.png" class="img-fluid r-stretch" alt="Scatter of quarterly change in unemployment rate against its own lag, colored by whether unemployment was rising or falling last quarter, with separate OLS fit lines showing steeper slope in the rising regime"><p><em>Quarterly <span class="math inline">\(\Delta u_t\)</span> against <span class="math inline">\(\Delta u_{t-1}\)</span>, split at zero — no grid search needed here, an economically motivated threshold. <strong>Rising regime</strong> (terracotta, <span class="math inline">\(\Delta u_{t-1}&gt;0\)</span>): visibly steeper slope — once unemployment starts rising, it tends to keep rising with strong momentum. <strong>Falling/stable regime</strong> (sky blue): weaker persistence. The Okun asymmetry, made concrete without any hidden state at all.</em></p>
</section>
<section id="smooth-transition-star" class="slide level2">
<h2>Smooth Transition: STAR</h2>
<blockquote>
<p>TAR switches sharply — the economy is entirely in one regime or the other. What if the transition itself is gradual?</p>
</blockquote>
<div class="eo-definition">
<p><strong>Smooth transition autoregression (STAR).</strong> Replace the indicator with a smooth function <span class="math inline">\(G_t=G(q_t;\gamma,c)\in[0,1]\)</span>:</p>
<p><span class="math display">\[
y_t = (1-G_t)(\phi_{1,0}+\boldsymbol\phi_1'\mathbf{y}_{t-1})+G_t(\phi_{2,0}+\boldsymbol\phi_2'\mathbf{y}_{t-1})+\varepsilon_t
\]</span></p>
<p><span class="math inline">\(q_t\)</span>: transition variable. <span class="math inline">\(c\)</span>: location — where <span class="math inline">\(G_t=0.5\)</span>. <span class="math inline">\(\gamma\)</span>: speed — large <span class="math inline">\(\gamma\)</span> approaches TAR’s sharp switch; small <span class="math inline">\(\gamma\)</span> gives a gradual, near-linear transition.</p>
</div>
</section>
<section id="two-flavors-of-smoothness" class="slide level2">
<h2>Two Flavors of Smoothness</h2>
<p><span class="math display">\[
\text{LSTAR: } G_t=\frac{1}{1+\exp(-\gamma(q_t-c))} \qquad\qquad \text{ESTAR: } G_t=1-\exp(-\gamma(q_t-c)^2)
\]</span></p>
<div class="eo-recap">
<p><strong>LSTAR</strong>: monotone — regime-2 weight rises smoothly as <span class="math inline">\(q_t\)</span> crosses <span class="math inline">\(c\)</span>. <strong>ESTAR</strong>: symmetric U-shape — regime-2 weight is high when <span class="math inline">\(q_t\)</span> is <em>far</em> from <span class="math inline">\(c\)</span> in <strong>either</strong> direction, low near <span class="math inline">\(c\)</span>. Natural when the middle of the distribution is “normal times” and both extremes represent crisis or boom.</p>
</div>
<p>As <span class="math inline">\(\gamma\to\infty\)</span> in LSTAR: <span class="math inline">\(G_t\to\mathbf{1}[q_t&gt;c]\)</span> — <strong>STAR nests TAR as a limiting case</strong>, not a separate family.</p>
</section>
<section id="ms-var-a-brief-map" class="slide level2 section-divider" data-background-color="#B87333" data-footer="false">
<h2>MS-VAR: A Brief Map</h2>
<div class="eo-section-label">
<p>Section 6</p>
</div>
</section>
<section id="the-natural-next-step-beyond-chapter-7" class="slide level2">
<h2>The Natural Next Step Beyond Chapter 7</h2>
<blockquote>
<p>Everything this chapter built was univariate — one series, one hidden regime. Chapter 7 built VARs for genuinely multivariate systems. What happens where the two frameworks meet?</p>
</blockquote>
<div class="eo-recap">
<p><strong>The MS-VAR</strong> — coefficient matrices <em>and</em> the covariance matrix of a VAR switch across regimes, governed by the same hidden Markov chain machinery this chapter developed. The intuition carries over directly: same prediction-correction logic, same smoothed-probability output, same labelling-indeterminacy challenge — now with the added richness of <strong>regime-dependent cross-variable dynamics</strong>.</p>
</div>
<p>Regime-dependent impulse responses matter economically: a monetary policy shock’s transmission to output and inflation (Chapter 7) may look genuinely different during a recession regime than during an expansion — not just in magnitude, but in shape and duration.</p>
</section>
<section id="the-landscape-briefly" class="slide level2">
<h2>The Landscape, Briefly</h2>
<div class="eo-recap">
<p><strong>Krolzig (1997)</strong> provides the canonical treatment and a typology of switching specifications: <strong>MSI</strong> (intercept-switching), <strong>MSM</strong> (mean-switching), <strong>MSA</strong> (AR-coefficient-switching), <strong>MSH</strong> (heteroscedastic variance-switching) — and combinations of these, exactly the same mean/variance-switching menu Section 2 built for the univariate case, now applied coefficient-matrix by coefficient-matrix.</p>
</div>
<div class="eo-hazard">
<p><strong>Software support is genuinely uneven.</strong> R offers <code>MSwM</code> and <code>MSBVAR</code>; Python’s <code>statsmodels.tsa.regime_switching</code> handles the univariate case cleanly but full MS-VAR estimation typically requires bespoke code. This chapter’s applied work stayed univariate for exactly this reason — not a limitation of the theory, a reflection of tooling maturity.</p>
</div>
</section>
<section id="recap" class="slide level2 recap-slide" data-background-color="#87A96B" data-footer="false">
<h2>Recap</h2>
<p>We relaxed the fixed-parameter assumption every prior chapter carried silently. The two-state Markov chain — transition probabilities, ergodic distribution, expected duration — gave a formal language for “the economy is always in one state or another, and we don’t know which.” The Hamilton filter turned that language into an algorithm: predict, then correct with new data, exactly the recursive logic underlying every filter in this course. Applied to GDP growth, the model recovered genuine recessions the data never labeled for it — and honestly missed the mild ones, and honestly lost to a plain ARIMA out of sample over a calm evaluation window, for reasons the Great Moderation itself explains. Threshold models offered the observable-state complement; MS-VAR, briefly mapped, extends everything to genuinely multivariate systems.</p>
<div class="eo-recap">
<p>Every element of the Hamilton filter — prior, likelihood, posterior, forward projection — has a direct counterpart waiting in Chapter 11. The only real difference: there, the hidden state is continuous, not discrete.</p>
</div>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p>The Hamilton filter solves a <strong>discrete</strong> inference problem: recover the probabilities of belonging to one of <span class="math inline">\(M\)</span> hidden states from a sequence of observations. Prediction projects the current state distribution through a finite transition matrix; the update applies Bayes’ rule with a Gaussian likelihood evaluated at the current observation.</p>
<p>Chapter 11’s <strong>Kalman filter</strong> solves the identical problem for a <strong>continuous</strong> hidden state. Instead of a probability vector over <span class="math inline">\(M\)</span> regimes, the state is a real-valued vector <span class="math inline">\(\boldsymbol\alpha_t\)</span> evolving via a linear Gaussian state equation. Instead of a finite transition matrix, a state transition matrix <span class="math inline">\(T\)</span> and Gaussian process noise. Instead of a mixture of <span class="math inline">\(M\)</span> Gaussians at each step, a single multivariate Gaussian, updated by the <strong>Kalman gain</strong> — the multivariate analogue of the weight Bayes’ rule assigns to new data relative to the prior. Chapter 11 builds this from scratch, starting with the local level model and working up to multivariate systems capable of extracting genuinely unobserved economic quantities: the output gap, trend inflation, the natural rate of interest. Nothing in it will feel unfamiliar — the architecture is already built.</p>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<div class="eo-keyterms">
<dl>
<dt>Markov-switching model / Hidden Markov chain</dt>
<dd>
Parameters shift between <span class="math inline">\(M\)</span> discrete regimes according to an unobserved first-order Markov chain; the state must be inferred, never directly observed.
</dd>
<dt>Transition probability matrix / Ergodic distribution</dt>
<dd>
<span class="math inline">\(P\)</span>, entries <span class="math inline">\(p_{ij}=\Pr(s_t=j\mid s_{t-1}=i)\)</span>; <span class="math inline">\(\boldsymbol\pi=P'\boldsymbol\pi\)</span>, the long-run regime shares, independent of initial conditions.
</dd>
<dt>Expected regime duration</dt>
<dd>
<span class="math inline">\(1/(1-p_{ii})\)</span> — average periods spent in regime <span class="math inline">\(i\)</span> before switching, under the geometric distribution a first-order Markov chain implies.
</dd>
<dt>MS-AR(<span class="math inline">\(k\)</span>) model</dt>
<dd>
Regime-specific mean (and optionally variance), AR dynamics capturing within-regime persistence, shared AR coefficients across regimes.
</dd>
<dt>Hamilton filter / Filtered probabilities / Smoothed probabilities</dt>
<dd>
The predict-update recursion extracting <span class="math inline">\(\Pr(s_t=j\mid y_1,\ldots,y_t)\)</span> in real time (filtered, causal) or <span class="math inline">\(\Pr(s_t=j\mid y_1,\ldots,y_T)\)</span> retrospectively (smoothed, sharper, not real-time).
</dd>
<dt>Labelling indeterminacy</dt>
<dd>
Swapping all regime-<span class="math inline">\(i\)</span> parameters with regime-<span class="math inline">\(j\)</span> leaves the likelihood unchanged; resolved by an ordering constraint or economically motivated starting values.
</dd>
<dt>Threshold autoregression (TAR) / SETAR</dt>
<dd>
AR coefficients switch based on whether an <em>observable</em> threshold variable crosses <span class="math inline">\(\gamma\)</span>; self-exciting when that variable is a lag of <span class="math inline">\(y_t\)</span> itself.
</dd>
<dt>Smooth transition autoregression (STAR)</dt>
<dd>
Generalizes TAR with a gradual logistic (LSTAR) or exponential (ESTAR) transition function; nests TAR as <span class="math inline">\(\gamma\to\infty\)</span>.
</dd>
<dt>MS-VAR</dt>
<dd>
Multivariate extension where coefficient and covariance matrices switch by regime; yields regime-dependent impulse response functions.
</dd>
</dl>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ECON-5371 · Time Series Analysis and Forecasting</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="10_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="10_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="10_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="10_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="10_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="10_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="10_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="10_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="10_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="10_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>